### ISSUE TITLE
Map labels, map opacity in dashboard.py

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#11]
It would be good to have a toggle button to enable or disable a map labels tile layer, to help people get oriented.

Having an opacity slider for the map tiles would also be good, since the map isn't always useful.

**Comment by brendancol** [comment]
I've superseded the other @jbednar PR with this one: https://github.com/bokeh/datashader/pull/47

**Comment by jcrist** [comment]
Fixed by #47, closing.
