### ISSUE TITLE
Tools for anomaly detection

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#116]
It would be good if we provided tools for highlighting or selecting anomalous values or other outliers, e.g. by making annotations on top of a datashaded plot.  Of course, this will require definitions of anomalous and outlier, e.g. in the form of a statistical model, and thus it will be fairly closely dependent on particular datasets.  Thus it's unlikely that we could solve this problem in general, but we could provide a framework that makes it easier to solve the problem in particular cases.  Alternatively, we may end up simply making some example notebooks showing how to highlight particular sorts of anomalies in specific cases, and leave the rest to the user to define and implement.

**Comment by thoth291** [comment]
As an example of something from real-life: a collection (up to 1000) of **csv files** of size (700 mb ~ 15M lines) have to be **visualized** (all at once - to **get meaningful ideas about outliers**) and analyzed/processed for those outliers to be excluded. After few iterations the resulted aggregated dataset will be stored in the file(s).

@jbednar - do you have any notebooks which might give me some starting points on any of the topics above?
I personally interested in visualizing using datashader but for the data being distributed across the nodes (using ipyparallel, dask or anything else).

Please advise.

Thanks in Advance!

**Comment by jbednar** [comment]
@thoth291, I'd recommend using dask as illustrated in the osm.ipynb example, extending it to use dask.distributed as well.  That way you should be able to use distributed data very cleanly.

I don't have any notebooks on these topics that I can provide.  We haven't yet implemented tools for going backwards from a selection on a Bokeh plot to isolating a set of bins in the aggregate array to formulating a query on the original dataset, and it's likely to be some time before we can do this.  If we had that, then identifying and removing outliers would be much simpler.  In the meantime, you can use hover information to try to see which of the curves or points need to be removed, and then remove those separately.  Whatever approach you take, we'd be happy to see what you come up with!

**Comment by thoth291** [comment]
Thanks @jbednar . That was my initial plan. I'll use dask to read the data. Then I'll try to use some of these pydaal examples: https://software.intel.com/en-us/node/682267, https://software.intel.com/en-us/node/682266 or this https://software.intel.com/en-us/node/682265.
Many more hours of work are left till I'll get it done though...

**Comment by jbednar** [comment]
The latest HoloViews 1.7.0 includes support for timeseries operations, including outlier detection, as illustrated at https://anaconda.org/jbednar/holoviews_datashader:

![image](https://cloud.githubusercontent.com/assets/1695496/25460910/a7294918-2aab-11e7-8510-18521a88c621.png)
