### ISSUE TITLE
Problem with castra census data

### ISSUE THREAD

**Issue by AlbertDeFusco** [bokeh/datashader#139]
Hi,

I've downloaded and extracted the census data to the `data/census.castra` directory, but I'm getting this error when using castra 0.1.7, dask 0.8.1 and python 3.5. Is there some other flag I need to pass?

```
In [1]: import dask.dataframe as dd

In [2]: df = dd.from_castra('data/census.castra')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-b49ecdd76267> in <module>()
----> 1 df = dd.from_castra('data/census.castra')

/Users/albert/Applications/anaconda3/envs/shader/lib/python3.5/site-packages/dask/dataframe/io.py in from_castra(x, columns)
    612     from castra import Castra
    613     if not isinstance(x, Castra):
--> 614         x = Castra(x, readonly=True)
    615     return x.to_dask(columns)
    616 

/Users/albert/Applications/anaconda3/envs/shader/lib/python3.5/site-packages/castra/core.py in __init__(self, path, template, categories, readonly)
     81                     "already exists.  Filename: %s" % self.path)
     82             self.load_meta()
---> 83             self.load_partitions()
     84             self.load_categories()
     85 

/Users/albert/Applications/anaconda3/envs/shader/lib/python3.5/site-packages/castra/core.py in load_partitions(self, loads)
    160     def load_partitions(self, loads=pickle.loads):
    161         with open(self.dirname('meta', 'plist'), 'rb') as f:
--> 162             self.partitions = loads(f.read())
    163         with open(self.dirname('meta', 'minimum'), 'rb') as f:
    164             self.minimum = loads(f.read())

UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 1: ordinal not in range(128)
```

**Comment by jbednar** [comment]
I don't think there's any flag to pass.  Castra's still under active development, and I've experienced some problems before about moving castra files between architectures and/or Python versions (which I've now completely forgotten about!).  I've tested it on a Mac with Python 2.7, castra 0.1.7, and dask 0.8.0, myself....

@jcrist may have some better suggestions...

**Comment by jbednar** [comment]
My suspicion would be that it's related to Python 3.5, since unicode issues always seem to be py3-related :-/.  datashader itself is tested with Python 3.5, but I don't see 3.5 in the automated Castra tests (only 3.4; https://travis-ci.org/blaze/castra), and moreover I don't know if there's a test to ensure that castra files created with one Python version work with others...

**Comment by AlbertDeFusco** [comment]
That's what I was thinking. 

Do you have the census data in other formats? I've been looking around the original website, but the data eludes me.

**Comment by jbednar** [comment]
We obtained the original data via a research collaboration, and for practical and economic reasons we can't publicly host multiple copies of large datasets.  For now, can you try running Python 2.7 just to get the data into a dataframe using the code above, and if that works then you can export it into a file on disk that pandas can read under 3.5?

**Comment by jbednar** [comment]
Note that what file format to use in examples is already an open issue (#129) ; if indeed this is a Castra problem we'll either need to fix Castra or choose a different (probably slower :-() format.  But I wouldn't want you to have to wait for us to finish that!

**Comment by AlbertDeFusco** [comment]
I got it to work in py35 by saving the file to HDF in my 2.7 environment. Thanks!

**Comment by jbednar** [comment]
Ok, thanks for the update!  It does sound like a problem using Castra under Python 3.5 with files generated on other versions.  I'll close this issue, since the other issue about needing to work on the file format now has a link to this issue anyway.
