### ISSUE TITLE
bokeh_ext not found

### ISSUE THREAD

**Issue by piyush121** [bokeh/datashader#155]
Hi,
I am getting following error when I am trying to import bokeh_ext:

`ImportError: No module named bokeh_ext`

**Comment by bryevdv** [comment]
Please share the exact code you used. It is impossible to diagnose without.

**Comment by piyush121** [comment]
```
import datashader as ds
from datashader.colors import Hot, inferno

import pandas as pd
df = pd.read_csv('nyc_taxi.csv')

# **Projection & Aggregation Step:**
# Map each record as a point centered by the fields `x_col` and `y_col` to
# a 400x400 grid of bins, computing the mean of `z_col` for all records in
# each bin.
cvs = ds.Canvas(plot_width=400, plot_height=400)
agg = cvs.points(df, 'pickup_latitude', 'pickup_longitude', ds.mean('total_amount'))

# **Transformation Step:**
# Interpolate the resulting means along a logarithmic color palette from
# "lightblue" to "darkblue"
img = tf.interpolate(agg, cmap=['lightblue', 'darkblue'], how='log')

```

**Comment by piyush121** [comment]
I am just trying to run the notebook files.
I installed all the required libraries as well.

**Comment by jbednar** [comment]
It looks like you are running a version of the notebook that's newer than your version of datashader.  We'll be making a new release that includes bokeh_ext, but for now, you can change "bokeh_ext" to "callbacks" and it should work.

**Comment by piyush121** [comment]
Yeah.. did that.. works now.
