### ISSUE TITLE
Coordinate transformation.

### ISSUE THREAD

**Issue by rainwoodman** [bokeh/datashader#175]
This probably belongs to Bokeh. Is there plan to support coordinate transformation in Glyphs? Namely, for visualizing astronomy data we would like to use an equal area projection. Even the degenerated cylindrical (z=sin(theta)) coordinate will give a much better perception on density of points.

This is probably relevant for geographical data as well.

**Comment by brendancol** [comment]
@rainwoodman, I don't think we have plans to support coordinate projection within datashader itself, but making sure all your input data is in the same coordinate system is important.  Have you tried projecting to equal-area before datashading?

**Comment by rainwoodman** [comment]
Thanks. I tried this. Is there a way to set the tick labels to the values
before transformation?

**Comment by jbednar** [comment]
The imminent bokeh release (0.12) does allow that, using a custom tick formatter implemented in https://github.com/bokeh/bokeh/pull/4504 .  There is a release candidate on the dev channel that includes that support, and the real release will be very soon now.

**Comment by rainwoodman** [comment]
Yes. It will be cool to try it out then. Shall I close this issue?

**Comment by jbednar** [comment]
I'll close it, thanks!
