### ISSUE TITLE
Testing and Updates for Bokeh 0.12.0 release coming next tuesday

### ISSUE THREAD

**Issue by brendancol** [bokeh/datashader#179]
- [ ] test Interactive Image
- [ ] test HoverLayer
- [ ] test categorical legend
- [ ] test color ramp legend

**Comment by jbednar** [comment]
Ready to close?

**Comment by linwoodc3** [comment]
i'm having trouble with getting the interactive image to work; followed the webinar, notebooks, and scipy talk....the picture doesn't update at all?

I am trying to visualize my Google Takeout Location history data (600k points over 4 years).  I cleaned the data using pandas, but can't get the interactive viz to work for datashader.  I can get the static plots no problem; the updating images like you have in the videos.  I've been looking at the bokek_ext but can't get it to work.  Any help?  

```python
import bokeh.plotting as bp
from bokeh.models.tiles import WMTSTileSource

bp.output_notebook()

def base_plot(tools='pan,wheel_zoom,reset',webgl=False):
    p = bp.figure(tools=tools,
        plot_width=int(900*1.5), plot_height=int(500*1.5),
        x_range=x_range, y_range=y_range, outline_line_color=None,
        min_border=0, min_border_left=0, min_border_right=0,
        min_border_top=0, min_border_bottom=0, webgl=webgl)
    
    p.axis.visible = False
    p.xgrid.grid_line_color = None
    p.ygrid.grid_line_color = None
    
    return p

from datashader.bokeh_ext import InteractiveImage

def image_callback(x_range, y_range, w, h):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.points(dfFinal, 'x', 'y', ds.count_cat('activity'))
    img = tf.colorize(agg, color_key=color_key, how='log')
    return tf.dynspread(img,threshold=.10, max_px=8)

p = base_plot()
# url="http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.png"
url="http://tile.stamen.com/toner-background/{Z}/{X}/{Y}.png"
tile_renderer = p.add_tile(WMTSTileSource(url=url))
tile_renderer.alpha=1.0 if background == "black" else 0.15
InteractiveImage(p, image_callback)
```

**Comment by jbednar** [comment]
Is this problem addressed by #224?

BTW, we're working on an example of using Google Takeout with datashader and should soon have a blog post about that; lots of cool stuff to visualize there!

**Comment by linwoodc3** [comment]
I just completed my Google Location History example (cleaning code from tar file below..if you can use anything).  Definitely can visualize a LOT and know where someone lives...drives..spends weekends, etc.  I did some filtering using pandas datetime to show only weekdays and business hours (code below).  Heck, with that type of filtering, you can find all the places someone "sleeps"

```python
# Visit this link and follow instructions to download your data
# https://takeout.google.com/settings/takeout?utm_source=ob&utm_campaign=takeout&hl=en

import tarfile
import json

# open the file containing your location history; this code assumes tar file
tar = tarfile.open('./takeout.tgz','r:gz')
data = tar.extractfile('.Takeout/Location History/LocationHistory.json')

# read the data from the file
final = data.readlines()

# join the bytes
locString = b"".join(final)


# convert the bytes to string
locString = locString.decode('utf-8')


# load history into a json
history = json.loads(locString)
tar.close() # remember to close the file

#function to extract highest confidence activity
def activityGetter(x):
    try:
        confidence =  x['activitys'][0]['activities'][0]['confidence']
        types = x['activitys'][0]['activities'][0]['type']
    except:
        confidence,types = "",""
    return confidence,types


# load Google takeout into pandas dataframe
import pandas as pd
df=pd.DataFrame(history)

# data cleaning 
# cleaning data and making columns
df['lon'] = df['locations'].apply(lambda x: x['longitudeE7']/10000000) #long
df['lat'] = df['locations'].apply(lambda x: x['latitudeE7']/10000000) #lat 

'''Tip to dividie by 10,000,000 came from 
http://www.lshift.net/blog/2014/09/30/lunchtime-hack-decoding-locationhistory/'''

df['timestamp'] = df['locations'].apply(lambda x: x['timestampMs']) #timestamp
df['accuracy'] = df['locations'].apply(lambda x: x['accuracy']) #accuracy
df['confidence'] = df['locations'].apply(lambda x: activityGetter(x)[0]) #confidence
df['activity'] = df['locations'].apply(lambda x: activityGetter(x)[1]) #type
dfFinal['activity']=df.activity.astype('category') # set category dtype

#time series index
df.set_index(pd.to_datetime(df.timestamp, unit="ms"), inplace=True, drop=True)

# a dataframe with business hours data only
df2 = df.between_time('05:00','18:00')

# now filter out only days of week; left with business hours during weekdays
dfFinal = df2[(df2.index.dayofweek < 5)][df['confidence']!= '']


# ready for datashader
```

**Comment by jbednar** [comment]
Yes, it's exciting but alarming.  @philippjfr, sounds like you're covering all this already in your blog post, but pointing you to it in case there is something you missed...

**Comment by linwoodc3** [comment]
One last question (somewhat related).  Do you all provide the code to "clean" the datasets.  I am still trying to figure out how you got the census data down to 3 columns from the gobbledy-gook it comes in from the census website.

**Comment by jbednar** [comment]
For Google Takeout, yes, we will provide that in the blog post.  For the NYC Taxi data, the cleaning code is in ``examples/taxi_preprocessing_example.py``.  For the census, we relied on our friends at the [Cooper Center](http://www.coopercenter.org/demographics/Racial-Dot-Map) (via a colleague at U. Indiana), who did all the preprocessing for us.  At some point I'd love to try to correlate the census data with other demographic information, so we're likely to revisit it and do the preprocessing again ourselves, but for now you'll have to contact the Cooper Center for more details.  Their [code is on Github](https://github.com/unorthodox123/RacialDotMap), but I don't know if it includes the cleaning steps.

**Comment by linwoodc3** [comment]
Thanks!
