### ISSUE TITLE
Add additional trajectory example

### ISSUE THREAD

**Issue by brendancol** [bokeh/datashader#182]
we need more line examples. Airplane data could be a good one.

**Comment by jbednar** [comment]
@philippjfr has one now; we just need to figure out how to make it public (as it uses 350MB of data).

**Comment by jbednar** [comment]
It's public now, at https://anaconda.org/jbednar/opensky/notebook (and opensky.ipynb in the examples directory).  It actually takes 780MB of data, though, so it's hard to recreate locally.
