### ISSUE TITLE
InteractiveImage Javascript TypeError 

### ISSUE THREAD

**Issue by andrejgaric** [bokeh/datashader#190]
Hello,
After watching great webinar talk about datashader lib from Dr. Bednar and Mr. Wang, I immediately started to play around with the library together with bokeh, another great library. 
By testing various notebook examples, such as trajectory example found on https://github.com/bokeh/datashader/blob/master/examples/trajectory.ipynb, I simply could not get the zoom-in data resampling/shading. The "granularity" of the data would stay the same and as I would zoom in, the graph would stay pixelated.
Looking the web console of the trajectory example run, I started getting "TypeError: plot.frame is undefined"  on each zoom in/out action.
With a little bit of luck I have managed to pinpoint the cause of the error to the JS code stored in jscode member of the InteractiveImage class, https://github.com/bokeh/datashader/blob/master/datashader/bokeh_ext.py.
I have changed the following snippet:
`
 var ranges = {{xmin: x_range.attributes.start,
                          ymin: y_range.attributes.start,
                          xmax: x_range.attributes.end,
                          ymax: y_range.attributes.end,
                          w: Math.floor(plot.frame.get('width')),
                          h: Math.floor(plot.frame.get('height'))}}
`
 to:
` var ranges = {{xmin: x_range.attributes.start,
                          ymin: y_range.attributes.start,
                          xmax: x_range.attributes.end,
                          ymax: y_range.attributes.end,
                          w: Math.floor(plot.model.attributes.width),
                          h: Math.floor(plot.model.attributes.height)}}`

This did work for me, but as I just started using datashader, I am unsure how the solution effects other parts of the library. Hopefully, it will help someone in similar situations for the time being.
Library versions:
datashader 0.3.0
bokeh 0.12.0

**Comment by philippjfr** [comment]
Thanks for reporting this. It is the result of changes introduced in bokeh 0.12. I've just opened a PR with a more robust approach, which will hopefully be merged soon. We're also still investigating how to get this functionality into bokeh in a more robust and flexible way.

**Comment by jbednar** [comment]
We should be able to release an updated datashader version very soon.  Meanwhile, installing bokeh 0.11.1 should fix the issue.

**Comment by andrejgaric** [comment]
Thanks guys, looking forward to the update.
