### ISSUE TITLE
Not recomputing in Jupyter notebook with bokeh 0.12

### ISSUE THREAD

**Issue by kgullikson88** [bokeh/datashader#195]
I am going through the examples folder, and noticed some weird behavior. When running the `nyc_taxi` example, I am not getting any dynamic recomputation when I zoom into the plot after the header "**10-million-point datashaded plots: interactive**". It zooms fine, there are no errors that I can find, but it never re-computes to get finer resolution. 

This problem is occurring when I run using a notebook server on a remote computer. I also installed bokeh and datashader on my laptop and everything works fine there. It turns out my laptop has bokeh 0.11.1, while the remote computer has bokeh 0.12.0. In both cases, I have datashader version 0.3.0

I downgraded bokeh on the remote computer, and now it works correctly.

**Comment by jbednar** [comment]
Yes, we are preparing a new release, hopefully by tomorrow, to address this incompatibility.  Meanwhile, the git version should have the correct behavior with Bokeh 0.12.

**Comment by brendancol** [comment]
@kgullikson88  `conda install -c bokeh datashader` and you should get the updated version which plays nicer with bokeh 0.12.0
