### ISSUE TITLE
ImportError: cannot import name 'downsample_aggregate' 

### ISSUE THREAD

**Issue by apiszcz** [bokeh/datashader#203]
Bokeh 0.11.1
datashader 0.1 with bokeh_ext from datashader 0.3.2

==

<ipython-input-2-fa9fd4d3897e> in <module>()
      7 import datashader as ds
      8 import datashader.transfer_functions as tf
----> 9 from datashader.bokeh_ext import InteractiveImage
     10 from functools import partial
     11 from datashader.utils import export_image

C:\p\via\lib\datashader\bokeh_ext.py in <module>()
     19 
     20 from . import transfer_functions as tf
---> 21 from .utils import downsample_aggregate, summarize_aggregate_values
     22 
     23 

ImportError: cannot import name 'downsample_aggregate'

**Comment by jbednar** [comment]
This code is mixing up files between different datashader releases, which isn't going to work in general.  Instead, you need to make sure that you use example notebooks that correspond to a specific release, and then it should all work.
