### ISSUE TITLE
bokeh 0.12, datashader 0.3.2, Python 3.5.1, Windows 10/64

### ISSUE THREAD

**Issue by apiszcz** [bokeh/datashader#207]
I'm using the following example from the examples folder. However the interactive pipeline 'image_callback' displays the WMS tiles correctly as one zooms, the data layer only magnifies when zooming in and does not re-render the layer based on zoom scale. I'm guessing something below is not correct. I'm running this in a Jupyter notebook

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import datashader as ds
import datashader.transfer_functions as tf
from datashader.bokeh_ext import InteractiveImage
from functools import partial
from datashader.utils import export_image
from datashader.colors import colormap_select, Greys9, Hot, viridis, inferno
from IPython.core.display import HTML, display
import bokeh.plotting as bp
from bokeh.models.tiles import WMTSTileSource

%time df=pd.read_pickle(r'D:\nyc_taxi\trip_data_pickup_wm.pkl')
df=df.ix[:1000000]
mask=((df['lat']>-90.0) & (df['lat']<90.0) & (df['lon']>-180.0) & (df['lon']<180.0) )
df=df[mask] # drop invalid records

bp.output_notebook()
plot_width=800
plot_height=600

x_range=[df['xwm'].min(),df['xwm'].max()]
y_range=[df['ywm'].min(),df['ywm'].max()]
NYC = x_range, y_range = ((-8242000,-8210000), (4965000,4990000))

def base_plot(tools='pan,wheel_zoom,box_zoom,reset,save,box_select,lasso_select',webgl=False):
    p = bp.figure(tools=tools, plot_width=plot_width, plot_height=plot_height,
        x_range=x_range, y_range=y_range, outline_line_color=None,
        background_fill_color='black', min_border=0, min_border_left=0, min_border_right=0,
        min_border_top=0, min_border_bottom=0, webgl=webgl)
    p.axis.visible = False
    p.xgrid.grid_line_color = None
    p.ygrid.grid_line_color = None    
    return p

def image_callback(x_range, y_range, w=plot_width, h=plot_height):
    cvs=ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg=cvs.points(df, 'xwm', 'ywm', ds.count('epoch'))
    img=tf.interpolate(agg,cmap=Hot)
    return tf.dynspread(img, threshold=0.25, max_px=4)

background="black"
export=partial(export_image, export_path="export", background=background)
cm=partial(colormap_select, reverse=(background=='black'))

p=base_plot(webgl=True)
url="http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.png"
tile_renderer = p.add_tile(WMTSTileSource(url=url))
tile_renderer.alpha=1.0 if background == "black" else 0.15

export(image_callback(*NYC),"NYC_hot")
InteractiveImage(p,image_callback)

**Comment by jbednar** [comment]
Those symptoms mean that the Python callback isn't running properly (the tiles update on the JavaScript side).  Which browser are you using?  If you look at the JavaScript console (see
http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers for how to do that with each browser), you may see a useful error message...

**Comment by apiszcz** [comment]
Thanks.
EDGE, and Chrome


EDGE (prior to following message I'm seeing a number HTTP404 messages on
missing jpy/notebook/notebook/static/components/bootstrap....

Python callback returned unexpected message: [object Object]
Function code (1) (14,13)
"Python callback returned unexpected message:"
[object Object]{buffers: Array[0], channel: "iopub", content: Object {...},
header: Object {...}, metadata: Object {...}, msg_id: "fdeebac7-49...",
msg_type: "error", parent_header: Object {...}}



CHROME:
Python callback returned unexpected message: Object {metadata: Object,
header: Object, parent_header: Object, msg_type: "error", content: Object…}

**Comment by apiszcz** [comment]
(function(x_range,y_range,cb_obj,cb_data,require
/**/) {

        // Define a callback to capture errors on the Python side
        function callback(msg){
          if (msg.msg_type == "execute_result") {
            if (msg.content.data['text/plain'] === "'Complete'") {
               if (Bokeh._queued.length) {
                   update_plot();
               } else {
                   Bokeh._blocked = false;
               }
               Bokeh._timeout = Date.now();
            }
          } else {
            console.log("Python callback returned unexpected message:", msg)
          }
        }
        callbacks = {iopub: {output: callback}};




FYI:
There are 140 of these type of not found URI errors, I am not user minrk,
... These issues may be due to the environment.

HTTP404: NOT FOUND - The server has not found anything matching the
requested URI (Uniform Resource Identifier).
(XHR): GET -
http://localhost:8888/Users/minrk/dev/jpy/notebook/notebook/static/components/bootstrap/less/mixins/reset-text.less

**Comment by apiszcz** [comment]
This may seem difficult to believe, however it appears the problem is
ujson. I had the ujson library in the path, and it was in the error message
under one of the calls, the message was stating that ujson could not
perform a translation. I removed the ujson module and now it rescales
properly on zoom, etc.. THANK YOU for the push to look at the javascript
interaction.

**Comment by jbednar** [comment]
The fix is now in master and should appear in the next datashader release.  Thanks for following up on the problem!

**Comment by apiszcz** [comment]
Thank you.
Is there any plan improvement for using datashader in bokeh without Jupyter?

**Comment by jbednar** [comment]
Yes, there's a plan, but we haven't made any progress on it so far, and would welcome contributions!
