### ISSUE TITLE
support pandas chunks

### ISSUE THREAD

**Issue by Casyfill** [bokeh/datashader#215]
as we talk about large datasets, it is often hard to read the whole dataset at once, and it takes a significant amount of time. same time, Pandas supports reading in chunks. It is easy to use datashader on chunks when we count items, but still, it would be awesome (and not that hard) to implement chunks support out of the box

Example with count:

```
dfs = pd.read_sql_query('SELECT lon, lat FROM tweets', con, chunksize=100000)
dfps = reprojDFS(dfs) # spatial reprojection on chunks

first = cvs.points(dfps.next(), 'x', 'y', ds.count)
agg = reduce(lambda x,y: x + cvs.points(y, 'x', 'y', ds.count), dfps, first)
```

however, for mean it requires  a bit more complicated solution

**Comment by jbednar** [comment]
Does this offer any benefit over using a dask dataframe for out of core processing, as illustrated in the osm.ipynb example and in https://github.com/bokeh/datashader/issues/206?

**Comment by jbednar** [comment]
Closing, assuming that those examples are sufficient, but feel free to re-open this and explain further if there is still an issue.
