### ISSUE TITLE
InteractiveImage not updating plot

### ISSUE THREAD

**Issue by simonkamronn** [bokeh/datashader#216]
It is my impression that `InteractiveImage(bokeh_plot, callback)` is supposed to update the plot using the callback function when zooming but I'm not able to make that happen even by running the example notebooks.

There's no errors, the zoomed image is just becoming more pixelated.

Bokeh version: 0.12.1
Datashader version: 0.3.0

**Comment by jbednar** [comment]
You'll need datashader version 0.3.2 (`conda install -c bokeh datashader`) to use Bokeh 0.12.x.

**Comment by simonkamronn** [comment]
Thanks.

**Comment by simonkamronn** [comment]
It seems to work if `callback` is a function that calculates new values, but if we have data stored in e.g. a dataframe such as
```
def update_image(x_range, y_range, w, h, df=df):
    cvs = ds.Canvas(x_range=x_range, y_range=y_range, plot_width=w, plot_height=h)
    agg = cvs.line(df, 'f_timestamp', 'x', agg=ds.any())
    return tf.interpolate(agg)

p = base_plot()
InteractiveImage(p, update_image, df=df)
```
the plot is not updated with higher resolution details when zooming. Not sure if this is intended?

**Comment by jbednar** [comment]
The various example notebooks should demonstrate updating with more resolution on zooming for dataframes, so no, what you are describing is not intended.  You may find a useful message on the [JavaScript console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers).  I'm assuming the function you wrote works fine on its own, without InteractiveImage?

**Comment by simonkamronn** [comment]
Using the JS console I discovered the ipywidgets  didn't even load but upgrading to version 5.0.0 seems to fix that. In the JS console I get this error when zooming: 
```
Uncaught TypeError: Cannot read property 'get' of undefined
  update_plot @ VM323:18
  c @ main.min.js:95
```

`update_image` works fine on its own.

**Comment by simonkamronn** [comment]
I found the error. I was importing `from datashader.callbacks import InteractiveImage` which should be from `datashader.bokeh_ext` instead.

**Comment by jbednar** [comment]
Ah, ok.  That used to to be the right way to do it, and maybe you had a stray .pyc file around that was making that fail to raise the appropriate error.  Glad it works now!
