### ISSUE TITLE
add noise_filter for aggregate

### ISSUE THREAD

**Issue by Casyfill** [bokeh/datashader#217]
I am aggregating a spatial representation of the average daytime for a lot of tweets.
It works fine, but there are plenty of tweets with glitched GPS coordinates, leading to the noise on the picture. It shouldn't be hard to remove them for count aggregation, but it would be also awesome to be able to use filters for other aggregates, such as mean. 

For example, I'd prefer to remove all points with less than 3 tweets in it, and color all points with standard deviation larger than 3 hours with a different color.

**Comment by jbednar** [comment]
You can see an example of removing low-count pixels (20 in this case) in the [OSM notebook](https://anaconda.org/jbednar/osm/notebook).  There should be no problem constructing a filter based on the counts, and then applying the filter to other aggregates; see examples of such cross-aggregate filtering in the [pipeline notebook](https://anaconda.org/jbednar/pipeline/notebook).  You just need to be very sure that all your aggregates are using the same x and y range and height and width, then combine in any way xarray allows.

To color some pixels differently depending on a mask, you can make a stddev aggregate, select only those pixels with high enough values, make a binary mask out of that, apply that to your count aggregate, colormap it with your preferred color range, and then do tf.merge() to stack that image on top of the image for the counts alone.  

So I think everything you're asking for is already supported, mainly by xarray operations but partly in datashader itself. Hope that all makes sense!
