### ISSUE TITLE
start a github gitter room for datashader

### ISSUE THREAD

**Issue by linwoodc3** [bokeh/datashader#223]
the Continuum Analytics project Dask has a gitter room.  It's good for discussion and suggestions and help (no top of the stackoverflow).

**Comment by jbednar** [comment]
That's a great suggestion, and the datashader team met yesterday to discuss it.  However, we decided that we do not have the resources to support a gitter room or a public discussion mailing list properly at this time.  

Datashader's initial development was externally funded, but its ongoing maintenance is on a volunteer basis, with all of the developers primarily being committed to other (paid) projects.  We don't want to offer a discussion forum that we don't have the manpower to monitor and address, and so we decided to focus on being able to respond to Github issues with the time we have available.  This could easily change over time, as we are seeking additional funding for new datashader development, so stay tuned!
