### ISSUE TITLE
Interactive bokeh_ext plots not working in examples

### ISSUE THREAD

**Issue by linwoodc3** [bokeh/datashader#224]
The interactive datashader graphic paired with bokeh doesn't work in the examples folders.

Can the examples be updated to have the code that enables interactive graphics that redraw the images based on pan/zoom actions?

The code update I'm requesting would enable an interactive image like the image in the Scipy 2016 video at the 17:25 mark:
https://www.youtube.com/watch?v=6m3CFbKmK_c

**Comment by bryevdv** [comment]
Please provide information about the versions go Bokeh and Datashader you have installed (all GH issues should always have such version information included). You may simply have a version mismatch, but it impossible to say without more information.

**Comment by linwoodc3** [comment]
Closing; you're right.  Once I updated to 0.4.0 and used shade, it worked.  thanks.  Closing.
