### ISSUE TITLE
Segfault with nan in y_range

### ISSUE THREAD

**Issue by johanfforsberg** [bokeh/datashader#229]
Another segmentation fault I encountered when entering nonsense data. This one should be simple to protect against I suppose.

```python
import datashader
import numpy as np
import pandas as pd

x = np.linspace(0, 10, 1000)
y = np.sin(x)
df = pd.DataFrame(dict(x=x, y=y))
cvs = datashader.Canvas(x_range=[0, 10], y_range=[np.NaN, 2],
                        plot_width=100, plot_height=100)
agg = cvs.line(df, "x", "y")
```

**Comment by jbednar** [comment]
Thanks!  I wasn't able to reproduce that problem using datashader master (g9fead6c):

![image](https://cloud.githubusercontent.com/assets/1695496/18280751/d6d8dc52-741f-11e6-86b3-a1120f3bca54.png)

but in any case I would expect it to be addressed by the [open PR](https://github.com/bokeh/datashader/pull/228) that should be merged soon.

**Comment by johanfforsberg** [comment]
Cool, looks like I found the same bug twice then. The "logy" branch throws a nice exception instead of crashing.

**Comment by jbednar** [comment]
The PR has been merged, so if you still see problems, let us know!
