### ISSUE TITLE
Unexpected behavior with line

### ISSUE THREAD

**Issue by johanfforsberg** [bokeh/datashader#230]
I'm seeing a strange behavior with the "line" aggregator. Running this sample code:
```python
import datashader
import numpy as np
import pandas as pd

y = [1, 0, 1, np.NaN, np.NaN, 0, 1, 0]
x = range(len(y))

df = pd.DataFrame(dict(x=x, y=y))
cvs = datashader.Canvas(x_range=[min(x), max(x)], y_range=[-1, 2],
                        plot_width=100, plot_height=100)
agg = cvs.line(df, "x", "y")
datashader.transfer_functions.shade(agg, cmap=["red"])
```
produces an image that does not draw a line from (5,0) to (6,1). I get exactly the same image if I replace x[5] with np.NaN. Somehow, having two NaN y-values in a row seems to cause an issue with drawing the following point.

**Comment by jbednar** [comment]
Thanks for reporting that with such a clear example!  That made it very easy to spot the problem.  Should be fixed by the above PR.
