### ISSUE TITLE
Update reference manual

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#237]
The online API documentation needs updating to match the current API.

**Comment by PeterDSteinberg** [comment]
I think it would help new users to have a documentation of many classes / functions from the code, like prototypes and docstrings as in dask documentation.  (I can help out with a docstring clean up PR and docs generation tool PR if needed.)

**Comment by PeterDSteinberg** [comment]
I'll add some comments here as a reminder for myself or whoever ends up tacking the docs issues:

 * There are qualitatively too many places where the interactive help shows `**kwargs` can be passed, but searching around for what are okay `kwargs` is confusing, e.g., the help on `hv.Points.sample` below.  Maybe we don't have to repeat all the ok `kwargs` in every doc string but at least provide reference to one place where they are all defined.
```
Signature: pts.sample(samples=[], closest=True, **kwargs)
Docstring:
Allows sampling of Dataset as an iterator of coordinates
matching the key dimensions, returning a new object containing
just the selected samples. Alternatively may supply kwargs
to sample a coordinate on an object. By default it will attempt
to snap to the nearest coordinate if the Element supports it,
snapping may be disabled with the closest argument.
File:      ~/Documents/ds/holoviews/holoviews/core/data/__init__.py
Type:      method
```

**Comment by jbednar** [comment]
Just to clarify, this issue is about datashader documentation, whereas `sample` is a HoloViews method, so issues with that method should be raised at https://github.com/ioam/holoviews/issues .

**Comment by PeterDSteinberg** [comment]
That was an oversight on my part (including holoviews docs issue here), but shows the need for cross linking between the projects in examples.  Working with these two libraries for a little over a month part time, I still get confused on the interaction between the viz libraries.  I think this is a general new user issue (have heard the same from 1 outside use) that we can address by more cross linking between the viz libraries' docs or mentioning in docstrings more specifically where the `kwargs` are being passed.  I got to this point by doing:
```
pts = hv.Points(np.random.uniform(0, 1, (10000, 2)))
agg = aggregate(pts, dynamic=False)
agg.sample?
pts.sample?
```

To the new user, it is not apparent on first interactive run of the code where to look for documentation related to the output of `aggregate`.
