### ISSUE TITLE
Support for column layout with InteractiveImage?

### ISSUE THREAD

**Issue by jordansamuels** [bokeh/datashader#250]
I like that the column layout can synchronize two or more bokeh time series (e.g. same time scale but different y axes), letting the user zoom with mousewheel on one and updating the others.  Is it possible to put several InteractiveImages in a column layout and achieve a similar synchronization?

**Comment by jbednar** [comment]
That is a very good question.  I think that should already be possible the same way that you [link Bokeh plots](http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/linking.html) in general, but I haven't tried it myself.  Could you try it out and show examples of either it working or any problems you have?

**Comment by jordansamuels** [comment]
Sure.  See https://anaconda.org/jordansamuels/interactiveimagecolumn/notebook .  I *think* I get what you are suggesting (make sure to re-use x_range and y_range from previous figure, which is the basis of the link you supplied); but it's not clear to me how to use column with InteractiveImage and/or sync up the InteractiveImage objects.

**Comment by jbednar** [comment]
That's a very helpful example, thanks!  The good news is that if you add `bp.show(column(s5, s6))` to the end of cell 10, it will happily lay out the two InteractiveImage plots on linked axes:

![image](https://cloud.githubusercontent.com/assets/1695496/19092043/98b93afc-8a4a-11e6-9301-64669fe5ffaf.png)

The bad news is that the plots aren't actually interactive. :-(  As you can see, zooming in doesn't work -- InteractiveImage doesn't currently seem able to keep track of state in multiple objects in the same Bokeh figure.  @philippjfr may be able to fix that if he gets time to look into it.

Meanwhile, Philipp and I are both maintainers of the [HoloViews](HoloViews.org) library, where we are adding Bokeh-based Datashader support that should soon make it possible to make linked axes using very simple code like:

```python
Aggregate(hv.Curve(df, kdims=['Time','a'])) + Aggregate(hv.Curve(df, kdims=['Time','b']))
```
That's untested, and won't give a zoomable plot as of today, but if all goes well something like that should work in HoloViews by tomorrow or so!  @philippjfr can give more details.

**Comment by jordansamuels** [comment]
@jbednar Thanks for looking into this.  I'll be happy to use HoloViews when it supports zoomable plots, so I'll keep checking for progress.  Again, great work with Bokeh/Datashader, it's really pretty sweet.

**Comment by philippjfr** [comment]
@jordansamuels [Here](https://anaconda.org/philippjfr/holoviews_datashader/notebook) is a notebook that demonstrates the datashader support in HoloViews. Obviously in the static version the dynamic features don't work, but if you grab the latest holoviews version from GitHub linked axes should work out of the box. I'll be documenting that notebook a bit better in the coming days so it can eventually make its way onto our website. Note also that this is still a work in progress, but we hope to make it stable by the next HoloViews release.

**Comment by jordansamuels** [comment]
@philippjfr and @jbednar  - checking in after a long break.  I am running the notebook that @philippjfr suggested to look at on Oct 6, and I do see some linked axes; however the dynamic updating doesn't seem to work on these.  For example, the "Linked Axes demo" uses `datashade(points) + decimate(points)` to create two side-by-side plots, but when I zoom into these using either the wheel zoom or the box zoom, the images don't dynamically update data.  However, all the single-axes plots do update dynamically; and if I use just `datashade(points)` or `decimate(points)` then I do get dynamic updating.

I'm using 

- Python 3.5.2 :: Anaconda custom (x86_64)
- datashader from git commit 83820878b11c41deede538600fa00a27e43b2b55
- holoviews from git commit 2b6b98bc1c92bf70f7e74d7590830e3b58431386
- bokeh 0.12.3-py35_0 from conda 
- Chrome 55.0.2883.95 (64-bit)
- OSX 10.11.6

I'm happy to file a separate issue if that's the best course.

Thanks,
Jordan

**Comment by jordansamuels** [comment]
@philippjfr for what it's worth, git bisect shows that https://github.com/ioam/holoviews/commit/86905fefaa46900620c07e02ca6c193118abb411 is first commit that it doesn't work for, using either  3eec053850284eeb551ee3be97faafc9461bf3d2 or master from datashader.

**Comment by philippjfr** [comment]
@jordansamuels Thanks for tracking that down, bit odd that adding titles to plots would break it but I'll try to work on it tonight. Definitely need some tests there.

**Comment by jordansamuels** [comment]
@philippjfr Another question (and I really am happy to file these somewhere else) - how do we make the plot widths of the above plots bigger?  I've tried various magics but cannot get anything to work.  Thanks a ton.

**Comment by philippjfr** [comment]
@jordansamuels For support questions you can join us on [Gitter](https://gitter.im/ioam/holoviews). Changing the width/height of the plot depends on what you're displaying (an annoyance that we hope to get rid of in future versions). If you print the repr of the object you're displaying I'll be able to help you.

**Comment by jbednar** [comment]
@jordansamuels, thanks for going above and beyond for a bug report!  I think once you start using git to help us figure out the precise moment a problem was introduced, you can now be considered an honorary HoloViews developer! :-)  @philippjfr, I don't see anything suspicious in that commit, but it does make sense that those changes could be the culprit, as they involve LayoutPlot, and this problem occurs only for Layouts, not isolated plots.

**Comment by jbednar** [comment]
Datashader plots should now "just work" in the latest HoloViews release (1.7.0), so please try it out and file a bug report at https://github.com/ioam/holoviews/issues if there are any problems.  Datashader plots in the same figure are all linked and interactive by default, as you can see in the new https://anaconda.org/jbednar/holoviews_datashader notebook if you download it and run it.  You'll probably need the git master version of datashader, but this support will all be in the next official release (0.5.0, which we have started on already), so I'll close this issue now.
