### ISSUE TITLE
Support for hover/legend with InteractiveImage?

### ISSUE THREAD

**Issue by jordansamuels** [bokeh/datashader#251]
When putting several series in the same interactive image, it's helpful to have a mouse-over/hover to identify the series and point; and/or a legend (ideally like dygraph legends, which are sort of liked docked hovers in that they always show the points and identify the series).  I see how to get hovers with non-interactive images from the `notebooks/hover_layer.ipynb` example; but it wasn't clear to me how to get this working with InteractiveImage.

**Comment by jbednar** [comment]
Right.  Unfortunately, making that work well is one of our older open issues (#126).  It's assigned to me, and I'd really like to see it working as well, but I haven't yet made progress on it.   I've recently worked out what I think is a good plan, though, and I hope to implement it soon!  It's listed at the end of that issue now.

Providing hover information has similar issues to legends, in that metadata about the plot needs to be provided in a principled way to InteractiveImage, but I'll try to make progress on legends first.

**Comment by tommycarstensen** [comment]
I'm very happy to be a tester on this.

**Comment by jbednar** [comment]
I'll go ahead and close this, as it's covered by #126.
