### ISSUE TITLE
PyPI Releases 0.3.2 and 0.4.0

### ISSUE THREAD

**Issue by jakirkham** [bokeh/datashader#253]
Would be nice to have PyPI releases for 0.3.2 and 0.4.0.

**Comment by jbednar** [comment]
There are no PyPI releases; see #164.

**Comment by jakirkham** [comment]
Then could I suggest deleting or hiding the PyPI stub.

xref: https://pypi.python.org/pypi/datashader

**Comment by jbednar** [comment]
That stub page is there to prevent people from registering the name datashader at PyPI, and to point them to conda, which the page does already.  Do I need to make that notice more prominent so that you would have noticed it?
