### ISSUE TITLE
Question about plotting lines

### ISSUE THREAD

**Issue by miguelgfierro** [bokeh/datashader#261]
I have 4 points in a map, corresponding to London, Madrid, Berlin and Paris. They are already in web mercator coordinates and as a dataframe.

| Latitude | Longitude |
| ------------- | ------------- |
| -1.209052e+04 |	6.720060e+06 |
| -4.105852e+05 |	4.932000e+06  |
| 1.294062e+06 |	6.143329e+06  |
|2.508090e+05 |	6.247991e+06 |

I want to create a map that conect the coordinates with lines in two by two. So I want a line between London and Madrid and another between Berlin and Paris. Using a the code of one of your examples what I get is 3 lines connecting each row with the next, so I got London-Madrid, then Madrid-Berlin and then Berlin-Paris.

```python
def create_image(x_range=x_range, y_range=y_range, w=plot_width, h=plot_height):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.line(dataframe, 'Latitude', 'Longitude',  ds.any())
    img = tf.shade(agg)
```

Is there an easy way to do this?

**Comment by jbednar** [comment]
Sure, you just need to insert a row of (NaN,NaN) entries anywhere you want a break in the line.  

Also, you should only use ``ds.any()`` if you don't expect issues with overplotting; it will make individual lines look nicer, but covers up issues when lines actually do overlap.

**Comment by miguelgfierro** [comment]
Thanks

**Comment by jbednar** [comment]
BTW, you should use datashader master from github for this, as we recently fixed a bug in processing lines that was causing some segments to be skipped.  We're hoping to have a corrected release very soon.
