### ISSUE TITLE
Project with datashader and football matches visualization

### ISSUE THREAD

**Issue by miguelgfierro** [bokeh/datashader#263]
I started a project that visualize the matches of football teams in the UEFA Champions League. The project is not finished yet and can be found [here](https://github.com/miguelgfierro/sciblog_support/blob/datashader/Visualization_of_Football_Matches/visualization_datashader.ipynb). 

The project takes the matches of all teams that have participated in the Champions and the coordinates of their stadiums. Then I plot each match since 1955 as a line between the coordinates of the stadiums of both teams. 

I'm not very happy with the visual appearance of the map. I would like to have something nicer. One option could be to change the map to a black and grey map of Europe and then plot the lines in white and grey. Do you know how to get a map like this? Here is the [map](https://github.com/miguelgfierro/sciblog_support/blob/datashader/Visualization_in_Data_Science/map.JPG).

Any other suggestion is welcomed

**Comment by jbednar** [comment]
Sounds like you can use the Stamen toner maps
(url 'http://tile.stamen.com/toner-background/{Z}/{X}/{Y}.png'), and use the alpha parameter to change the brightness level to make it gray and black.

**Comment by miguelgfierro** [comment]
thanks!
