### ISSUE TITLE
Census data information

### ISSUE THREAD

**Issue by OliverEvans96** [bokeh/datashader#265]
Hello,

Thanks all for the great package! The census data notebook is very insightful. I'm trying to apply the same technique with the same dataset (from  the link in examples/datasets.yml) to my own town, but I can't figure out what format the location data is in. The only hint I can find is that the columns are labeled 'meterswest' and 'metersnorth'. I tried calculating the distance in meters along latitude and longitude lines from (0,0), but I'm off by a few orders of magnitude. It may well be an error in my calculation, but I think I'm probably just attempting the conversion incorrectly.

Here's my code: 
```
# Isolate Akron, Ohio census data

# Imports
import dask.dataframe as dd
import numpy as np

print("Read data")
# Read all data
df = dd.read_hdf('census.h5','census')

# Load region to isolate
akc = np.array([
        [-81.694679,40.904172],    # min: lat, long
        [-81.311531 41.185889]])   # max: lat, long

akw = akc[:,0]  # West (longitude degrees)
akn = akc[:,1]  # North (latitude degrees)

# Radius of Earth
R = 6.371e6

# Coordinates in meters
akn_m = R*akn
akw_m = akw*R*np.cos(np.pi*akn/180)

print("akw_m = ({:.3e},{:.3e})".format(*akw_m))
print("akn_m = ({:.3e},{:.3e})".format(*akn_m))

print("W Extrema: ({:.3e},{:.3e})".format(
        df['meterswest'].min().compute(),
        df['meterswest'].max().compute()))
print("N Extrema: ({:.3e},{:.3e})".format(
        df['metersnorth'].min().compute(),
        df['metersnorth'].max().compute()))

print("Determine rows")
# Isolate Akron, Ohio
df_ak = df[(df['meterswest']>akw_m[0]) & \
         (df['meterswest']<akw_m[1]) & \
         (df['metersnorth']>akn_m[0]) & \
         (df['metersnorth']<akn_m[1])]

# Write to hdf
print("Write to HDF")
df_ak.to_hdf('akron_census.h5','akron_census',format='table')
```

This generates the following output:
```
Read data
akw_m = (-3.934e+08,-3.899e+08)
akn_m = (2.606e+08,2.624e+08)
W Extrema: (-1.388e+07,-7.453e+06)
N Extrema: (2.818e+06,6.336e+06)
Determine rows
Write to HDF
```

The resulting HDF file is empty since, as you can see, my calculated region is way out of bounds for the data. So if anybody knows the correct conversion from latitude/longitude to 'meterswest'/'metersnorth', I would love to know!

Furthermore, can anyone provide a source for the data? It seems to be legitimate census data, but I can't imagine that a table with a row for every individual is the format provided by the Census Bureau. Data I've found describes the population by region.

Thanks,
OIiver

**Comment by jbednar** [comment]
I haven't looked at your code above, but you can find out the Web Mercator bounding box for your town using the function ``lnglat_to_meters(df, longitude="longitude", latitude="latitude")`` in [datashader/utils.py](https://github.com/bokeh/datashader/blob/master/datashader/utils.py#L139).  You'd need to put the latitude and longitude coordinates into a dataframe with those columns, or adapt that code to make your own function that doesn't need a dataframe.  That function isn't in the released version of datashader yet, but we are gearing up for a release as soon as we can tidy up some pesky details, and in the meantime you can just copy that bit from the source code.

As for the source of the data, the top of the census.ipynb notebook in examples/ describes where the data came from and how there came to be one row per person, which is based on work by the [Cooper Center](http://www.coopercenter.org/demographics/Racial-Dot-Map).  In short, the data from the smallest supported region (the census tract level) was used to synthesize one row per person, randomly within that area, and with race and population counts matching the census data.  The result is just the same as if we had the genuine (but unavailable!) census data, but randomized on the census tract level.

**Comment by jbednar** [comment]
Actually, I've reopened this, as we may as well go ahead and make another lnglat function for use in the census notebook, so that user-visible coordinates are in longitude, latitude, which is much more useful for ongoing work.  I'll close this once I've done that.

**Comment by OliverEvans96** [comment]
Thanks!

**Comment by jbednar** [comment]
Ok, I updated [lnglat_to_meters](https://github.com/bokeh/datashader/blob/c796fb45ccb00bbd284c49afb6ed2bfd657df856/datashader/utils.py#L139) so that it will work for bare coordinates, numpy arrays, or dataframes, so you should now easily be able to compute the ranges needed in Web Mercator coordinates to select a region of interest.  Let me know if you find any problems!

**Comment by OliverEvans96** [comment]
Thanks so much for being so quick and helpful. I really appreciate it.
Perhaps the census notebook should mention that the data is in Web Mercator
units, and mention the lnglat_to_meters function? Especially if a new
release is coming soon, it might be a good bit to add.

Thanks,
Oliver

**Comment by jbednar** [comment]
Definitely.

**Comment by jbednar** [comment]
@OliverEvans96, please try out the new census.ipynb and see if that helps you do what you want!  You'll need the very latest github version of datashader.
