### ISSUE TITLE
Minimal Datashader/Bokeh-Server Example

### ISSUE THREAD

**Issue by Andres9713** [bokeh/datashader#271]
Hi, I have began using this extremely powerful library for plotting time-series of hundreds of neurons simultaneously recorded using calcium imaging techniques (~15x10^6 points). I have used both the datashader and the bokeh server, and both work very well. However, for my use-case using both of these together is the logical choice. The 'dashboard' example shows that this can be accomplished, however, it is a particularly complex example, with many interactive and mutually dependent components - so it's significantly difficult to determine what are the _minimal and sufficient elements necessary for a simple use-case of datashader in the bokeh-server_ (for instance, a time-series or an image which supports  zooming and panning using datashader within a simple bokeh server). After reading through some forums I realized that I was likely not the only one who could benefit from such an example - so I wanted to add this to the 'wishlist'. Thank you for all the hard work, and for this much needed graphing solution!

**Comment by jbednar** [comment]
I think what you're asking for is covered by https://github.com/bokeh/datashader/issues/147, which doesn't help as that's just another issue and not a PR. :-/

That said, as mentioned there, we are currently focusing on supporting datashader from within [HoloViews](http://holoviews.org), which is working very well already.  You can see an example in https://anaconda.org/jbednar/census-hv/notebook , which shows that it's now simple to instantiate an interactive datashader plot, even if you need to overlay or lay it out with multiple other datasets.  

The last little piece of the puzzle is for HoloViews elements to be fully usable with Bokeh Server, which is partially true but unfortunately not yet fully completed: https://github.com/ioam/holoviews/issues/694

So, it should soon be simple to use datashader with bokeh server, but it's not there just yet. @philippjfr may be able to describe recent progress.

**Comment by alexcombessie** [comment]
Hi! I have been running through the [notebook example](https://anaconda.org/jbednar/tseries/notebook) on time series. I would be interested in a simple example of a Bokeh Server adaptation. Thanks a lot for your interesting and hard work!

**Comment by jbednar** [comment]
There's a complete 30-line example of a Bokeh Server datashader app at the end of  [pyviz tutorial 1](https://pyviz.github.io/pyviz/tutorial/01_Workflow_Introduction.html), and the entire 
[pyviz tutorial](https://pyviz.github.io/pyviz/tutorial/00_Welcome.html) will help explain everything involved.
