### ISSUE TITLE
Build / Upload Python 3.6 conda packages

### ISSUE THREAD

**Issue by brendancol** [bokeh/datashader#272]

**Comment by StevenCHowell** [comment]
datashader seems to work for me with Python 3.6 (installed using the recommended method into a python 3.6 virtual env: `conda install -c bokeh datashader`).  Is 3.6 not actually supported yet?

**Comment by jbednar** [comment]
3.6 is not supported yet, in the sense that we are not testing against it.  But if it works, great; when we start testing we can quickly close this issue!
