### ISSUE TITLE
InteractiveImage callbacks to Flask app 

### ISSUE THREAD

**Issue by Thru-Echoes** [bokeh/datashader#279]
I have created responsive Flask web apps using Bokeh plots, such as (https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/responsive.py). 

I also have a IPython / Jupyter notebook running InteractiveImage with this code: 

```
def base_plot(tools='pan,wheel_zoom,reset',webgl=False):
    p = bp.figure(tools=tools,
                  plot_width=int(900*1.0), plot_height=int(500*1.0),
                  x_range=x_range, y_range=y_range, outline_line_color=None,
                  min_border=0, min_border_left=0, min_border_right=0,
                  min_border_top=0, min_border_bottom=0, webgl=webgl)

    
    p.axis.visible = False
    p.xgrid.grid_line_color = None
    p.ygrid.grid_line_color = None
    
    return p

def image_callback(x_range, y_range, w, h):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.points(df, 'meterswest', 'metersnorth', ds.count_cat('race'))
    img = tf.shade(agg, color_key=color_key, how='log')
    return tf.dynspread(img,threshold=0.75, max_px=8)

p = base_plot()

#url="http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.png"
url="http://tile.stamen.com/toner-background/{Z}/{X}/{Y}.png"
tile_renderer = p.add_tile(WMTSTileSource(url=url))
tile_renderer.alpha=1.0 if background == "black" else 0.15

InteractiveImage(p, image_callback)

```
However, how can I use InteractiveImage with the plot and the callback in the same way in a Flask web app? It seems like InteractiveImage cannot process the callbacks to and from the server (Flask) script?

**Comment by jbednar** [comment]
Right.  InteractiveImage only supports the Jupyter notebook, at least for now (see #147).  We've worked out [partial support](https://github.com/ioam/holoviews/pull/959) for using Bokeh server via the HoloViews project, but have not yet released (or merged) that.  I'll close this as a duplicate, but I hear your pain! :-/
