### ISSUE TITLE
Some kind of global variable naming issue regarding `datashader` in holoviews

### ISSUE THREAD

**Issue by PeterDSteinberg** [bokeh/datashader#292]
Try:
```
from holoviews.operation.datashader import datashade
import datashader
```

It will fail on the second command.

Reverse it and still fails on second command:

```
import datashader
from holoviews.operation.datashader import datashade
```
Suggests some confusion regarding the use of identifier `datashader` within `holoviews.operation`.

This problem exists in Jupyter notebook, but if you go into Ipython console you can do the imports in either order.

**Comment by philippjfr** [comment]
Thanks for reporting this @PeterDSteinberg. Would you mind reopening it on the holoviews repo, I suspect it's something to do with absolute imports in holoviews.
