### ISSUE TITLE
Taxi example claims to be in latlon but is in meters

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#30]
The download_sample_data.py script converts latitude and longitude to meters (in Web Mercator coordinates), but writes those values back to the original fields.  Those fields are named pickup_longitude, pickup_latitude, dropoff_longitude, and dropoff_latitude, which is very confusing when reading code that uses this dataset, because they no longer contain latitudes or longitudes.  Should presumably store the computed values in pickup_x, pickup_y, dropoff_x, and dropoff_y instead.

**Comment by jcrist** [comment]
Closed by #31 and #32.
