### ISSUE TITLE
Add memory usage benchmarks

### ISSUE THREAD

**Issue by gbrener** [bokeh/datashader#305]
Adding benchmarks for memory usage could illuminate details about datashader's runtime performance that were previously not being measured. Among other things we should benchmark memory usage for different dataset sizes, and see how memory usage changes as datasets grow.

**Comment by gbrener** [comment]
# Memory usage takeaways

With memory usage measurements in place, we can start validating the dataframe size and how it corresponds to memory usage in the overall datashader benchmarks. The following statements were added to filetimes.py immediately before the first call to `timed_agg`, to display the dataframe's per-column memory usage and data types:
```
mem_usage = df.memory_usage(deep=True)
if p.dftype == 'dask':
    mem_usage = mem_usage.compute()
print('DEBUG:', mem_usage)
mem_usage_total = mem_usage.sum()
print('DEBUG: DataFrame size:\t\t\t{} MB'.format(mem_usage_total / 1e6))
for colname in df.columns:
    print('DEBUG: column "{}" dtype: {}'.format(colname, df[colname].dtype))
```

The results show that the memory usage of the persisted dask dataframe align with what we'd expect:
```
$ python filetimes.py times/census.parq dask census meterswest metersnorth race --debug --cache=persist
DEBUG: Cache "persist" mode enabled
DEBUG: Memory usage (before read):      135.733248 MB
DEBUG: read_parquet(times/census.parq, index=False, columns=['meterswest', 'metersnorth', 'race'])
DEBUG: Force-loading Dask dataframe
DEBUG: Memory usage (after read):       5997.34272 MB
DEBUG: Index                 560
metersnorth    2453400032
meterswest     2453400032
race            306677314
dtype: int64
DEBUG: DataFrame size:                  5213.477938 MB
DEBUG: column "meterswest" dtype: float64
DEBUG: column "metersnorth" dtype: float64
DEBUG: column "race" dtype: category
DEBUG: Memory usage (after agg1):       7549.800448 MB
DEBUG: Memory usage (after agg2):       8219.004928 MB
times/census.parq            dask    Aggregate1:017.39 (009.76+007.63)  Aggregate2:003.94  In:05213483268  Out:00000625044  Total:026.49
```

Let's verify these calculations:
- Number of rows of data in dataset: 306675004
- `metersnorth` and `meterswest` are each represented as 8-byte double-precision floats (`np.float64`); our expected size for each column is 8 x 306675004 = 2453400032 (correct)
- `race` is a categorical data type; each categorical value is represented by a 1-byte integer, which makes it fairly close. The 2310 bytes leftover indicate that pandas probably stores some metadata for categoricals
- the `index` looks strange at first, but after some digging it starts to make sense: in v0.18.0 pandas began using a [RangeIndex](http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html#range-index) which dramatically reduces index size by storing metadata about the index (as long as it's sequential). One dataframe index typically takes up about 80 bytes, but since dask was used here, each of the 7 partitions kept its own separate index (probably a RangeIndex), which leads to a total of 560 bytes

**Comment by jbednar** [comment]
Great! And do they change in the appropriate ways (and with what impact on performance?) when changing from doubles to floats?

**Comment by gbrener** [comment]
Yep, they do change, and they do affect performance. I'm opening a PR shortly with some additions to filetimes.py so we can more-easily observe / reproduce this, and see how changing the data types affects performance. I'll also update the post above with the results after converting doubles to floats.

**Comment by jbednar** [comment]
Thanks.  And how does the total memory usage for the process compare with the total usage for the dataframes reported here?  The difference between those two numbers should tell us a lot...

**Comment by gbrener** [comment]
@jbednar I added another section with results for the float32 data after running PR #323 and writing out the data as float32 instead of float64.

**Comment by jbednar** [comment]
Excellent!

**Comment by gbrener** [comment]
Closing this issue, since the memory-usage benchmarks have been added.
