### ISSUE TITLE
Memory usage of min/max operations due to nan-checking

### ISSUE THREAD

**Issue by gbrener** [bokeh/datashader#336]
@martindurant contributed the following in #332 :

> Memory plot when running in pure-pandas mode (script extract below):
>
> ![figure_1](https://cloud.githubusercontent.com/assets/6042212/25600058/30fdd378-2eaf-11e7-8d18-a2b9ef1142a8.png)
>
> The data size is ~5GB, but there are regular excursions to almost 8GB. There being four for each agg, I would suspect these are calculating max/min on the axes - snakeviz seems to confirm this. I note with interest the following:
>
> ```
> In [7]: %time df.metersnorth.min()  # pandas with NaN checking
> CPU times: user 1.58 s, sys: 898 ms, total: 2.48 s
> Wall time: 2.5 s
> Out[7]: 2818291.5
>
> In [8]: %time df.metersnorth.values.min()  # pure numpy
> CPU times: user 167 ms, sys: 1.58 ms, total: 169 ms
> Wall time: 167 ms
> Out[8]: 2818291.5
> I don't know what datashader has to say about null-handling, but it would be well worthwhile to determine the nulls only once up-front than to pay the cost every time.
> ```
>
> Here is the script I used for pure-pandas:
>
> ```
> import fastparquet
> import datashader as ds
> import time
>
> plot_width = 900
> plot_height = int(900*7.0/12)
> t0 = time.time()
> df = fastparquet.ParquetFile('census.parquet').to_pandas()
> t1 = time.time()
> print('Load', round(t1-t0, 1))
> cvs = ds.Canvas(5, 5)
> agg = cvs.points(df, 'meterswest', 'metersnorth')
> t2 = time.time()
> print('Agg1', round(t2-t1, 1))
> cvs = ds.Canvas(plot_width, plot_height)
> agg = cvs.points(df, 'meterswest', 'metersnorth')
> t3 = time.time()
> print('Agg2', round(t3-t2, 1))
> ```
>
> -EDIT-
>
> ```
> In [4]: @numba.njit()
>    ...: def nan_min_max(arr):
>   ...:     mi = arr[0]
>   ...:     ma = arr[0]
>   ...:     for i in range(1, len(arr)):
>   ...:         v = arr[i]
>   ...:         if np.isnan(v):
>   ...:             continue
>   ...:         if v > ma:
>   ...:             ma = v
>   ...:         if v < mi:
>   ...:             mi = v
>   ...:     return ma, mi
> In [11]: %time nan_min_max(np.asarray(df.metersnorth.values))
> CPU times: user 327 ms, sys: 1.23 ms, total: 328 ms
> Wall time: 327 ms
> Out[11]: (6335972.0, 2818291.5)
> ```

**Comment by gbrener** [comment]
Among my commits to #344 was dropping to numpy's `np.nanmin()` and `np.nanmax()`, which saves a lot of time. I also added `@memoize` to the bounds calculations, but only for dask dataframes (dask dataframes are immutable; for this to work with pandas we'd need to calculate the hash - which can be done with `dask.dataframe.hashing` - but takes much longer than recalculating the min/max). So provided that the same dask dataframes are being passed to datashader repeatedly, the min/max calculations will be done much more quickly, and only once.

Regarding the pandas side of things, I also used numba to speed up that code so that it only does one pass through the data. Someone who is more familiar with dask might want to add a similar approach to the dask bounds calculation code - I struggled to find a straightforward way to do it (i.e. add custom numba code into the dask graph) that yielded a performance improvement.

**Comment by jbednar** [comment]
> the memory usage is understood.

So with those changes, the memory usage no longer increases periodically like that?

**Comment by gbrener** [comment]
I don't know how @martindurant generated those graphs - perhaps he'd be able to confirm here with the code from PR #344 ?

**Comment by martindurant** [comment]
https://github.com/fabianp/memory_profiler#time-based-memory-usage
but I can have a look sometime...
