### ISSUE TITLE
Add micro benchmarks to test suite

### ISSUE THREAD

**Issue by jbcrail** [bokeh/datashader#346]
I recommend using `pytest-benchmark` for simple benchmarks. This was already useful for testing potential performance regressions in recent PRs.

This is not meant to replace the existing benchmarking tool for file format performance (`examples/filetimes.py`).

**Comment by jbednar** [comment]
Sounds good!  We could consider [airspeed velocity](http://asv.readthedocs.io) as well/in addition.
