### ISSUE TITLE
Taxi data set download

### ISSUE THREAD

**Issue by zzzrpagliari** [bokeh/datashader#361]
The location of the taxi dataset might be incorrect. 

`AttributeError: 'DataFrame' object has no attribute 'pickup_longitude'`

**Comment by p-himik** [comment]
They have moved their data to http://pugetsoundlidar.ess.washington.edu/lidardata/restricted/be_ascii/pslc2016/2016King_County_Delivery_1_bare_earth_ascii/
The page requires authorization, but after you register and login you can download all of the datasets manually to the `examples/data` directory - that should work.

**Comment by jbednar** [comment]
@p-himik, I've opened a new issue #362 about that problem, which is for the Lidar dataset, not the taxi dataset.  Thanks for the tip, in any case!

@zzzrpagliari, can you clarify what is giving you that error message?  The taxi dataset we provide has a column `pickup_x`, which is the longitude already converted to Web Mercator coordinates.  I don't think we have any code that relies on `pickup_longitude`, but if we do, that's presumably an error, in which case please re-open this issue and give us an idea where that is.
