### ISSUE TITLE
Lidar downloads broken

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#362]
```
$ python download_sample_data.py 
Skipping Austin, TX Elevation Data
Skipping NYC Crime Data
Skipping NYC Taxi Data
Skipping Mobile, AL Landsat8 Data
Skipping Puget Sound Lidar 1 of 25
Downloading Puget Sound Lidar 2 of 25
[################################] 1/1 - 00:00:00
FAILED ON 7Z examples/data/q47122d2102.7z
Traceback (most recent call last):
  File "download_sample_data.py", line 307, in <module>
    main()
  File "download_sample_data.py", line 304, in main
    _process_dataset(d, output_dir, here)
  File "download_sample_data.py", line 292, in _process_dataset
    _extract_downloaded_archive(output_path)
  File "download_sample_data.py", line 239, in _extract_downloaded_archive
    _unzip_7z(output_path)
  File "download_sample_data.py", line 204, in _unzip_7z
    arc = Archive7z(open(fname, 'rb'))
  File "anaconda/envs/ds/lib/python3.6/site-packages/py7zlib.py", line 746, in __init__
    raise FormatError('not a 7z file')
py7zlib.FormatError: not a 7z file
```

We should probably make it not an error when there are issues with individual downloads like this. In any case, looks like the LIdar examples have been moved somewhere:

<font size="+2">Error 404: &nbsp;&nbsp;</font> Page not found.
<p>If this is a bad link on the pugetsoundlidar web site, don't wait
for harvey and diana to
read the error logs.
Write to
<a href="mailto:hgreen@u.washington.edu">hgreen@u.washington.edu</a> or
to <a href="mailto:ANorton@psrc.org"><span
 style="text-decoration: underline;">Andy Norton</span></a>.
Give the URL of the referring page.
</p>
<p>Some restructuring is underway.
If something fails, try from the <a
 href="http://pugetsoundlidar.org">top</a> of the tree.
</p>
<p><a href="http://gis.ess.washington.edu/sorry.html">Sorry</a> for the
inconvenience.

**Comment by jbednar** [comment]
Acclording to p-himik:

They have moved their data to http://pugetsoundlidar.ess.washington.edu/lidardata/restricted/be_ascii/pslc2016/2016King_County_Delivery_1_bare_earth_ascii/
The page requires authorization, but after you register and login you can download all of the datasets manually to the examples/data directory - that should work.

If it requires authorization, we presumably need to mirror the data ourselves instead.

**Comment by PeterDSteinberg** [comment]
Addressing this now - uploading zip of gnd files to S3.  I'll simplify the notebook to remove the un7zipping requirement in favor of just reading .gnd (3 column text files) from the S3 zip, but will add a note saying the full data set can be downloaded from Puget Sound Lidar Consortium at the new URL's.
