### ISSUE TITLE
Syntax error during manual build

### ISSUE THREAD

**Issue by bjfar** [bokeh/datashader#364]
I tried doing a manual install, just cloning the git repository and running setup.py, however I get a syntax error reported during the build process:

```
copying build/lib.linux-x86_64-2.7/datashader/compiler.py -> build/bdist.linux-x86_64/egg/datashader
byte-compiling build/bdist.linux-x86_64/egg/examples/streaming.py to streaming.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/raster.py to raster.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/filetimes.py to filetimes.pyc
  File "build/bdist.linux-x86_64/egg/examples/filetimes.py", line 101
    print("DEBUG: Force-loading Dask dataframe", flush=True)
                                                      ^
SyntaxError: invalid syntax
```

This seems to be some Python 3 syntax, while I am still on Python 2.7.11, however I didn't notice anywhere that Python 3 was a requirement. So I guess this is a bug?

The build is still going, it seems like this error did not stop the process and it is taking a while to compile Pandas or some such, but anyway I assume the above is not supposed to happen.

**Comment by jbednar** [comment]
The filetimes.py script is Python3 only, but that's just a testing script we use, not anything you need in practice.  Not sure which `setup.py` option you're using, but `python setup.py develop` should work fine.

**Comment by bjfar** [comment]
I just did `python setup.py install`. Anyway the build did indeed complete eventually, but apparently there is something wrong in the linking to llvm, because I get the following

```
>>> import datashader
Gtk-Message: Failed to load module "canberra-gtk-module"
/usr/local/lib/python2.7/dist-packages/odo-0.5.0-py2.7.egg/odo/backends/pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/datashader-0.5.0-py2.7.egg/datashader/__init__.py", line 5, in <module>
    from .core import Canvas
  File "/usr/local/lib/python2.7/dist-packages/datashader-0.5.0-py2.7.egg/datashader/core.py", line 8, in <module>
    from .utils import Dispatcher, ngjit
  File "/usr/local/lib/python2.7/dist-packages/datashader-0.5.0-py2.7.egg/datashader/utils.py", line 7, in <module>
    import numba as nb
  File "/usr/local/lib/python2.7/dist-packages/numba-0.33.0-py2.7-linux-x86_64.egg/numba/__init__.py", line 9, in <module>
    from . import config, errors, runtests, types
  File "/usr/local/lib/python2.7/dist-packages/numba-0.33.0-py2.7-linux-x86_64.egg/numba/config.py", line 11, in <module>
    import llvmlite.binding as ll
  File "/usr/local/lib/python2.7/dist-packages/llvmlite-0.18.0-py2.7-linux-x86_64.egg/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/usr/local/lib/python2.7/dist-packages/llvmlite-0.18.0-py2.7-linux-x86_64.egg/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/usr/local/lib/python2.7/dist-packages/llvmlite-0.18.0-py2.7-linux-x86_64.egg/llvmlite/binding/ffi.py", line 50, in <module>
    raise e
OSError: /usr/local/lib/python2.7/dist-packages/llvmlite-0.18.0-py2.7-linux-x86_64.egg/llvmlite/binding/libllvmlite.so: cannot open shared object file: No such file or directory
```

I built llvm 4.0 from source because datashader required it and the llvm versions in the Debian repositories are not that new. It seemed to build and install just fine, but perhaps llvmlite is something different I need to build?

**Comment by jbednar** [comment]
Oh, I wouldn't build anything from source; anything to do with LLVM is very tricky.  Can't you just install datashader using ``conda install -c bokeh datashader``, then remove it using ``conda uninstall datashader``, then do ``python setup.py develop`` in this directory?  I don't think the build step offers anything useful here; it's all just pure python.

**Comment by jbednar** [comment]
I'll close this as it seems like you got things working in #363, and I don't think we need to debug ``python setup.py build``.

**Comment by bjfar** [comment]
Oh this is on a different machine to #363. That was on a cluster, this is just on my laptop with Debian Jessie. And I don't have anaconda on my laptop, and didn't want to use it since I have an older machine with a SSD so I have limited disk space and can't afford multiple copies of things. So as far as I could tell I had no choice but to build llvm since version 4.0 isn't in the Debian repositories yet.
