### ISSUE TITLE
Implement gridtools regridding based on lazy arrays in xarray.Dataset

### ISSUE THREAD

**Issue by PeterDSteinberg** [bokeh/datashader#372]
This regridding and resampling tool is built with numba for numpy arrays: https://github.com/CAB-LAB/gridtools

[`earthio` will be modified in this issue 12](https://github.com/ContinuumIO/earthio/issues/12) to make xarray backends for NetCDF, HDF4, HDF5, GeoTiff files, loading them into `xarray.DataArray`s that are lazy (`dask.array`s) within `xarray.Dataset`s.

**Comment by PeterDSteinberg** [comment]
We may want to consider ghosted dask arrays?

**Comment by gbrener** [comment]
@PeterDSteinberg to be honest I'm not yet familiar with what dask refers to as "ghosted arrays", but I plan to look into this issue once I replace rasterio in datashader.

**Comment by philippjfr** [comment]
I also aware dask had this concept but [here](http://dask.pydata.org/en/latest/array-ghost.html) is the documentation. The idea being that to regrid on a chunked array you have to correctly handle the edges of the chunks so you need some overlap between them.

**Comment by gbrener** [comment]
This is done, as PRs #375 and #389 are now merged.
