### ISSUE TITLE
Instructions to "manually install from the repository" not working?

### ISSUE THREAD

**Issue by ceball** [bokeh/datashader#381]
I'm new to datashader, so forgive me if I'm doing something wrong, but I get the following error when I follow the "manually install from the repository" instructions at https://github.com/bokeh/datashader/blob/master/README.md:
 
```
$ git clone https://github.com/bokeh/datashader.git && cd datashader
[...]
$ conda install -c bokeh --file requirements.txt
Fetching package metadata .............

PackageNotFoundError: Package missing in current osx-64 channels: 
  - param >=1.5.1,<2.0
```

If I additionally supply ``-c ioam``, things seem to work.

**Comment by jbednar** [comment]
Oops; I think we requested that param be updated to 1.5.1 on the main anaconda channel, but it doesn't look like that ever happened.  No problem; 1.5.0 should be fine for datashader, so I've relaxed its requirements.txt specification to 1.5.0.

**Comment by philippjfr** [comment]
>No problem; 1.5.0 should be fine for datashader, so I've relaxed its requirements.txt specification to 1.5.0.

For datashader it's fine but for working with holoviews, param 1.5.1 is explicitly required, that's why 1.5.1 was released in the first place.

**Comment by jbednar** [comment]
Right; that's why it's still 1.5.1 in examples/environment.yml, which includes holoviews examples.  Hopefully we can have 1.5.1 on main soon enough and make it all match.

**Comment by jbednar** [comment]
In case it matters, 1.5.1 is now required in datashader/examples/environment.yml, but holoviews looks like it's currently requiring 1.5.1 anyway; not sure if that's just master or also the released holoviews version requiring that.
