### ISSUE TITLE
New install fails when getting sample data

### ISSUE THREAD

**Issue by dartdog** [bokeh/datashader#395]
I have a Conda 3.6 env on Ubuntu 16.04 I got DS installed using PIP (having previously installed all prerequisites and tested out holoviews..)
I went to install the sample data using the download_sample_data.py file in the created datashader-examples directory (after I finally located and installed pylzma)
I got a bunch of files but then it failed as follows..

```
Downloading Mobile, AL Landsat8 Data 1 of 1
[################################] 835670/835670 - 00:06:52
Downloading Puget Sound Lidar 1 of 25
[################################] 1/1 - 00:00:00
FAILED ON 7Z /home/tom/datashader-examples/data/q47122d2101.7z
Traceback (most recent call last):
  File "download_sample_data.py", line 307, in <module>
    main()
  File "download_sample_data.py", line 304, in main
    _process_dataset(d, output_dir, here)
  File "download_sample_data.py", line 292, in _process_dataset
    _extract_downloaded_archive(output_path)
  File "download_sample_data.py", line 239, in _extract_downloaded_archive
    _unzip_7z(output_path)
  File "download_sample_data.py", line 204, in _unzip_7z
    arc = Archive7z(open(fname, 'rb'))
  File "/home/tom/anaconda3/envs/py36n/lib/python3.6/site-packages/py7zlib.py", line 746, in __init__
    raise FormatError('not a 7z file')
py7zlib.FormatError: not a 7z file
```

looks like it failed on the 1st section of the Puget Sound Lidar data>>> q47122d2101.7z
What do I need to do? looks like all I have is the NYC Taxi and NYC Crime...

**Comment by jbednar** [comment]
I'm not sure what you mean about installing datashader using pip, because we only provide it on conda, but in any case you should be able to fix it by installing the latest development release:

```
conda install -c bokeh/label/dev datashader
```

We're working on a full new 0.6 release, but in the meantime this should address the fact that the lidar examples were moved on their external site.

**Comment by ceball** [comment]
> I have a Conda 3.6 env on Ubuntu 16.04 I got DS installed using PIP (having previously installed all prerequisites and tested out holoviews..)

Just to be clear, do you mean you installed all the prerequisites using conda, and then you did ``pip install -e .`` inside a git clone of datashader? Or did you mean something else?
