### ISSUE TITLE
hammer_bundle modifies nodes dataframe inplace

### ISSUE THREAD

**Issue by philippjfr** [bokeh/datashader#399]
When running ``hammer_bundle`` it seems to modify 'x' and 'y' columns in the supplied ``nodes`` dataframe inplace. There are two solutions to this issue, either the coordinates of the nodes and edges should be in the same space as the input in which case the inplace modification wouldn't be an issue OR the operation should make a copy of the dataframe and return the adjusted nodes.

**Comment by jbednar** [comment]
This looks like an easy thing to fix, and something that definitely should be done:

```
def _convert_graph_to_edge_segments(nodes, edges):
    ...
    nodes['x'] = minmax_scale(nodes['x'])
    nodes['y'] = minmax_scale(nodes['y'])
```

Just need to make a new dataframe that's a copy, and use that in the rest of the function.  Temporarily copying the nodes shouldn't necessarily be that expensive, assuming there are usually many more edges than nodes.
