### ISSUE TITLE
Travis does not follow any one set of installation instructions

### ISSUE THREAD

**Issue by ceball** [bokeh/datashader#404]
Travis has its own list of dependencies (I'm not counting extra testing dependencies), and those dependencies don't appear to be the exactly same as one of examples/environment.yml, conda.recipe/meta.yaml, or requirements.txt.

I think travis should be testing one of the existing lists, but which one? Maybe examples/environment.yml, since that's the one suggested to developers, and the travis build is really for developers? I'm not sure.

**Comment by ceball** [comment]
Sorry, not just the dependencies, but also e.g. ``python setup.py develop --no-deps`` vs instruction to ``pip install -e .``.

**Comment by jbednar** [comment]
I must admit that I have no idea why there are so many lists of dependencies.  Can't we have just one list for datashader itself, and generate any other list needed for that?  As we aren't currently testing the examples, I'd assume that this one main (fairly lean) set of dependencies should be the one used by Travis, not the full environment.yml.

Using pip install -e makes sense to me.

**Comment by ceball** [comment]
I could create a poll and everyone could vote for their favorite dependencies/versions! Or maybe we need a new dependencies/requirements specification format to rule them all? ;)

I'm not yet in a position to know why the lists are different - maybe there are valid reasons, and the lists have been arrived at through hard-won practical experience.

Can someone make 'required', 'optional',  'examples' lists out of these? (Or something like that.)

# travis

```
conda install
   1. colorcet
   2. dask
   3. datashape  
   4. numba
   5. numpy
   6. odo  
   7. pandas
   8. param
   9. pillow
  10. pytest
  11. rasterio
  12. scikit-image
  13. toolz
  14. xarray

testing
  conda install
    a. matplotlib
    b.
    c. 
```

# appveyor

```
conda install
   1. colorcet
   2. dask
   3. datashape  
   4. numba
   5. numpy
   6. odo
   7. pandas  
   8. param
   9. pillow
  10. pytest
  11. rasterio -c conda-forge
  12. scikit-image
  13. toolz
  14. xarray

testing:
  conda install 
    a. matplotlib
    b.
    c. 
```

# conda/meta.yaml

```
channels:
  - numba

run:
   1. colorcet >=0.9.0
   2. dask >=0.7.6
   3. datashape >=0.5.1
   4. numba >=0.24.0
   5. numpy >=1.7
   6. odo >=0.4.1
   7. pandas >=0.15.0
   8. param >=1.5.0,<2.0
   9. pillow >=3.1.1
  10.
  11.
  12.
  13. toolz >=0.7.4
  14. xarray >=0.9.6
    + python

test:
   a. 
   b. pytest >=2.8.5
   c. rasterio >=1.0
```

# pip/requirements

```
 1. colorcet
 2. dask
 3. datashape >= 0.5.1
 4. numba >= 0.24.0
 5. numpy >= 1.7
 6. odo >= 0.4.1
 7. pandas >= 0.15.0
 8. param >=1.5.0,<2.0
 9. pillow
10.
11.
12.
13. toolz
14. xarray
```

# examples/environment.yml

```
conda channels:
 - bokeh/label/dev
 - conda-forge
 - ioam/label/dev
 - ioam
 - scitools/label/dev

conda dependencies:
 1. colorcet
 2. dask
 3.
 4. numba
 5. numpy
 7. pandas
 8. param>=1.5.1
 9. 
10. pytest
11. rasterio
12. scikit-image
13. 
14. xarray>=0.9.6 # For xarray.open_rasterio()

  + attrs
  + bokeh>=0.12.6dev3
  + cartopy
  + dill
  + distributed
  + fastparquet
 #+ fastcache # Only required for Python2, for the dashboard/
  + geoviews
  + holoviews
  + iris
  + jupyter
  + jupyter_dashboards
  + krb5
  + matplotlib
  + networkx 
  + paramnb
  + pyproj
  + pytables
  + python=3.6
  + python-snappy
  + requests
  + scipy
  + shapely
  + snappy
  + statsmodels
  + tblib
  + yaml
 
 pip dependencies
  + cachey
  + webargs
```

**Comment by ceball** [comment]
Also, datashader/__init__.py has a test() method. Maybe travis should use that to run the tests, and the README should also say to run the tests that way? Otherwise I'd be tempted to remove test() from __init__.py. (Maybe __init__.test() is there for platforms where ``py.test`` is not available as an executable script? I can't guess another reason, but there could well be one.)
