### ISSUE TITLE
"Conflicting sizes for dimension" error when data is nan-only

### ISSUE THREAD

**Issue by p-himik** [bokeh/datashader#414]
Datashader 0.5.0

Example of a stacktrace:
```
  File "/home/p-himik/[...]", line 56, in create_datashader_image
    img = tf.shade(agg, cmap=['yellow', 'blue'], how='linear')
  File "/home/p-himik/soft/anaconda3/envs/cedar2/lib/python3.5/site-packages/datashader/transfer_functions.py", line 351, in shade
    return _interpolate(agg, cmap, how, alpha, span)
  File "/home/p-himik/soft/anaconda3/envs/cedar2/lib/python3.5/site-packages/datashader/transfer_functions.py", line 182, in _interpolate
    return Image(agg.data.view(np.uint32), coords=agg.coords, dims=agg.dims, attrs=agg.attrs)
  File "/home/p-himik/soft/anaconda3/envs/cedar2/lib/python3.5/site-packages/xarray/core/dataarray.py", line 224, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
  File "/home/p-himik/soft/anaconda3/envs/cedar2/lib/python3.5/site-packages/xarray/core/dataarray.py", line 87, in _infer_coords_and_dims
    'coordinate %r' % (d, sizes[d], s, k))
ValueError: conflicting sizes for dimension 'x_axis': length 2000 on the data but length 1000 on coordinate 'x_axis'
```

Root cause:
`datashader.transfer_functions._interpolate`, lines
```python
masked = data[~mask]
        if len(masked) == 0:
            return Image(agg.data.view(np.uint32), coords=agg.coords, dims=agg.dims, attrs=agg.attrs)
```
When `agg.data` has an incompatible with this statement dtype (e.g. float64), there will be that ValueError.

**Comment by jbednar** [comment]
Thanks for the info!  I'm a bit confused why agg.data would ever have a type that varied, but in any case, we added code on May 8 to handle the all-NaN case.  Please try the development version of 0.6 using ``conda install -c bokeh/label/dev datashader`` to see if that fixes the issue.  It sounds like it might not, but it would be good to know either way.

**Comment by jbednar** [comment]
I'm closing this issue assuming it must be working for you now, but if you've tried the dev release and it didn't improve things, please re-open and explain what happens now.

**Comment by p-himik** [comment]
Sorry, I got caught up in other things.

Nope, still doesn't work, the exception is the same.

MWE:
```python
import datashader as ds
import numpy as np
import pandas as pd
from datashader import transfer_functions as tf

df = pd.DataFrame(np.full([3, 2], np.nan), columns=['x', 'y'])
cvs = ds.Canvas(100, 100, x_range=(0, 1), y_range=(0, 1))
agg = cvs.line(df, 'x', 'y', ds.max('y'))
img = tf.shade(agg)
```

**Comment by p-himik** [comment]
I'm not a collaborator (yet :) ), so I can't re-open an issue that I didn't close.

**Comment by jbednar** [comment]
Fixed by https://github.com/bokeh/datashader/pull/439 .
