### ISSUE TITLE
bundling module doesn't exist !

### ISSUE THREAD

**Issue by maresk** [bokeh/datashader#416]
`---> 14 from datashader.bundling import directly_connect_edges, hammer_bundle
     15 from datashader.utils import export_image
     16 

ModuleNotFoundError: No module named 'datashader.bundling'`

Getting the above error, weird because datashader import work just fine. Installed it via Conda as recommended. If not pushed to Conda repos yet any chance it could be pushed in the near future ?

**Comment by jbcrail** [comment]
Thanks for reporting this issue!

Edge bundling is only available in the dev releases at this time. You can install `datashader` with:

```
conda remove datashader
conda install -c bokeh/label/dev datashader
```

The `remove` subcommand is needed to make sure conda doesn't get confused in the future.

**Comment by kfedotov-fulcrm** [comment]
Hi, I am getting this same error even after 
conda install -c bokeh/label/dev datashader
is there anything else that might be needed to be updated?

We are trying to run an edge bundling tutorial
Thanks

**Comment by jbednar** [comment]
Edge bundling is now fully released, and should work out of the box if you follow the instructions for setting up your environment at https://github.com/bokeh/datashader/tree/master/examples .  If you have any trouble, please post your error messages and we can probably figure it out.

**Comment by kfedotov-fulcrm** [comment]
Thank you for the reply, the issue seems to be on our end with anaconda environments.
