### ISSUE TITLE
Datashader TypingError

### ISSUE THREAD

**Issue by dwervin** [bokeh/datashader#419]
Following the nyc_taxi Notebook as an example, I receive this error when calling cvs.points().

%%time
cvs = ds.Canvas(plot_width=plot_width, plot_height=plot_height, x_range=x_range, y_range=y_range)
#agg = cvs.points(df2, 'x_cord', 'y_cord', ds.count('cust_type'))
agg = cvs.points(df2, 'X_CORD', 'Y_CORD', ds.count('DGROUP'))

img = tf.shade(agg, cmap=["white", 'darkblue'], how='linear')

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-32-20b7970f00fe> in <module>()
----> 1 get_ipython().run_cell_magic('time', '', 'cvs = ds.Canvas(plot_width=plot_width, plot_height=plot_height, x_range=x_range, y_range=y_range)\n#agg = cvs.points(df2, \'x_cord\', \'y_cord\', ds.count(\'cust_type\'))\nagg = cvs.points(df2, \'X_CORD\', \'Y_CORD\', ds.count(\'DGROUP\'))\n\nimg = tf.shade(agg, cmap=["white", \'darkblue\'], how=\'linear\')')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2113             magic_arg_s = self.var_expand(line, stack_depth)
   2114             with self.builtin_trap:
-> 2115                 result = fn(magic_arg_s, cell)
   2116             return result
   2117 

<decorator-gen-60> in time(self, line, cell, local_ns)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\execution.py in time(self, line, cell, local_ns)
   1183         else:
   1184             st = clock2()
-> 1185             exec(code, glob, local_ns)
   1186             end = clock2()
   1187             out = None

<timed exec> in <module>()

C:\ProgramData\Anaconda3\lib\site-packages\datashader\core.py in points(self, source, x, y, agg)
    171         if agg is None:
    172             agg = count()
--> 173         return bypixel(source, self, Point(x, y), agg)
    174 
    175     def line(self, source, x, y, agg=None):

C:\ProgramData\Anaconda3\lib\site-packages\datashader\core.py in bypixel(source, canvas, glyph, agg)
    345     agg.validate(schema)
    346     canvas.validate()
--> 347     return bypixel.pipeline(source, schema, canvas, glyph, agg)
    348 
    349 

C:\ProgramData\Anaconda3\lib\site-packages\datashader\utils.py in __call__(self, head, *rest, **kwargs)
     40         typ = type(head)
     41         if typ in lk:
---> 42             return lk[typ](head, *rest, **kwargs)
     43         for cls in getmro(typ)[1:]:
     44             if cls in lk:

C:\ProgramData\Anaconda3\lib\site-packages\datashader\pandas.py in pandas_pipeline(df, schema, canvas, glyph, summary)
     28 
     29     bases = create((height, width))
---> 30     extend(bases, df, x_st + y_st, x_range + y_range)
     31 
     32     return finalize(bases, coords=[y_axis, x_axis], dims=['y_axis', 'x_axis'])

C:\ProgramData\Anaconda3\lib\site-packages\datashader\glyphs.py in extend(aggs, df, vt, bounds)
    106             ys = df[y_name].values
    107             cols = aggs + info(df)
--> 108             _extend(vt, bounds, xs, ys, *cols)
    109 
    110         return extend

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    328                                 for i, err in failed_args))
    329                 e.patch_message(msg)
--> 330             raise e
    331 
    332     def inspect_llvm(self, signature=None):

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    305                 argtypes.append(self.typeof_pyval(a))
    306         try:
--> 307             return self.compile(tuple(argtypes))
    308         except errors.TypingError as e:
    309             # Intercept typing error that may be due to an argument

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    577 
    578                 self._cache_misses[sig] += 1
--> 579                 cres = self._compiler.compile(args, return_type)
    580                 self.add_overload(cres)
    581                 self._cache.save_overload(sig, cres)

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, args, return_type)
     78                                       impl,
     79                                       args=args, return_type=return_type,
---> 80                                       flags=flags, locals=self.locals)
     81         # Check typing error if object mode is used
     82         if cres.typing_error is not None and not flags.enable_pyobject:

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    702     pipeline = Pipeline(typingctx, targetctx, library,
    703                         args, return_type, flags, locals)
--> 704     return pipeline.compile_extra(func)
    705 
    706 

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(self, func)
    355         self.lifted = ()
    356         self.lifted_from = None
--> 357         return self._compile_bytecode()
    358 
    359     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in _compile_bytecode(self)
    663         """
    664         assert self.func_ir is None
--> 665         return self._compile_core()
    666 
    667     def _compile_ir(self):

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in _compile_core(self)
    650 
    651         pm.finalize()
--> 652         res = pm.run(self.status)
    653         if res is not None:
    654             # Early pipeline completion

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in run(self, status)
    241                     # No more fallback pipelines?
    242                     if is_final_pipeline:
--> 243                         raise patched_exception
    244                     # Go to next fallback pipeline
    245                     else:

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in run(self, status)
    233                 try:
    234                     event(stage_name)
--> 235                     stage()
    236                 except _EarlyPipelineCompletion as e:
    237                     return e.result

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in stage_nopython_frontend(self)
    447                 self.args,
    448                 self.return_type,
--> 449                 self.locals)
    450 
    451         with self.fallback_context('Function "%s" has invalid return type'

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
    803 
    804         infer.build_constraint()
--> 805         infer.propagate()
    806         typemap, restype, calltypes = infer.unify()
    807 

C:\ProgramData\Anaconda3\lib\site-packages\numba\typeinfer.py in propagate(self, raise_errors)
    765         if errors:
    766             if raise_errors:
--> 767                 raise errors[0]
    768             else:
    769                 return errors

C:\ProgramData\Anaconda3\lib\site-packages\numba\typeinfer.py in propagate(self, typeinfer)
    126                                                    lineno=loc.line):
    127                 try:
--> 128                     constraint(typeinfer)
    129                 except TypingError as e:
    130                     errors.append(e)

C:\ProgramData\Anaconda3\lib\site-packages\numba\typeinfer.py in __call__(self, typeinfer)
    435     def __call__(self, typeinfer):
    436         with new_error_context("typing of intrinsic-call at {0}", self.loc):
--> 437             self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
    438 
    439 

C:\ProgramData\Anaconda3\lib\site-packages\numba\typeinfer.py in resolve(self, typeinfer, typevars, fnty)
    399             desc = context.explain_function_type(fnty)
    400             msg = '\n'.join([head, desc])
--> 401             raise TypingError(msg, loc=self.loc)
    402 
    403         typeinfer.add_type(self.target, sig.return_type, loc=self.loc)

TypingError: Failed at nopython (nopython frontend)
Invalid usage of + with parameters ((int64 x 3), pyobject)
Known signatures:
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
 * (complex64, complex64) -> complex64
 * (complex128, complex128) -> complex128
 * (uint8,) -> uint64
 * (uint16,) -> uint64
 * (uint32,) -> uint64
 * (uint64,) -> uint64
 * (int16,) -> int64
 * (int8,) -> int64
 * (int64,) -> int64
 * (int32,) -> int64
 * (float32,) -> float32
 * (float64,) -> float64
 * (complex64,) -> complex64
 * (complex128,) -> complex128
 * parameterized
File "..\..\..\..\ProgramData\Anaconda3\lib\site-packages\datashader\glyphs.py", line 102
[1] During: typing of intrinsic-call at C:\ProgramData\Anaconda3\lib\site-packages\datashader\glyphs.py (102)

This error may have been caused by the following argument(s):
- argument 4: Unsupported array dtype: object

**Comment by jbednar** [comment]
It's hard to debug anything without a complete example including the data files involved, but from the messages it looks like there may be non-numeric data in one of the columns provided for datashading.

**Comment by dwervin** [comment]
Yes, the data in the DGROUP field is non-numeric.  I guess it's not clear to me what the ds.count() funtion is counting.

**Comment by jbednar** [comment]
Ah.  If you leave off ", ds.count('DGROUP')" entirely, it will already count the number of points, because the default aggregate is `ds.count()` anyway.  

If you supply a column name explicitly, as you did here, it checks that column for NaNs and then doesn't count that point if there's a NaN in that column, which only really makes sense for numeric data.  Not sure what you were hoping to do with DGROUP, but maybe you don't need to include it at all?

**Comment by dwervin** [comment]
OK, that makes sense.

I was hoping I might be able to leverage the information in DGROUP also the help highlight or colorize points differently also.  The information in that field is a logical area name to identify a dispacth group for dispatching utility workers.  It would be interesting to visualize calls in particular dispatch groups, differently then another dispatch group.

And we also have the customer type field that would be interesting to visualize as well.

I guess I kinda had my SQL hat on thinking in terms of "group by".  Is this sort of approach possible with datashader?

**Comment by jbednar** [comment]
Ah, you want something like:

```
df2.DGROUP = df2.DGROUP.astype('category')
agg = cvs.points(df2, 'X_CORD', 'Y_CORD', ds.count_cat('DGROUP'))
```

`count_cat` will aggregate into *n* different arrays, if there are *n* different categories.  Search for `count_cat` in the nyc_taxi notebook for an example of how to use it.
