### ISSUE TITLE
bokeh downgrade with conda install?

### ISSUE THREAD

**Issue by timothydmorton** [bokeh/datashader#420]
I just tried to `conda install datashader` and it was requiring me to downgrade bokeh from `0.12.6` to `0.12.4`.  Is this actually necessary, or does something just need to be updated in the conda requirements for datashader?

**Comment by jbednar** [comment]
Yes, the released version of datashader (0.5) depends on things in Bokeh that changed in 0.12.5. 
 Datashader is overdue for a new release, but in the meantime you can install datashader from the dev channel if you want to use it with newer Bokeh releases: ``conda install -c bokeh/label/dev datashader``
