### ISSUE TITLE
Remove dynd

### ISSUE THREAD

**Issue by jcrist** [bokeh/datashader#43]
I originally used dynd to store the results of aggregation because:
- It has builtin representation of missingness for non-float types
- Better support for record (and nested record) types
- (planned) support for variable length strings

However, I no longer think this was a good decision, and propose to remove it from the codebase. Reasons:
- Bugs, segfaults, crashes. These are all too common right now. Progress is rapidly being made to clean this up (and I'm impressed with how quickly the dynd team is improving things), but currently it's a bit of a hassle to use.
- Missing features. Most functionality I'd want in an nd-array library currently doesn't exist. Same as above, this is changing rapidly, but currently I'm casting to numpy arrays for most operations.
- (partial) incompatibility with much of the pydata ecosystem. Dynd arrays support the buffer protocol, and so can work fine with many things *if the dtype is numpy compatible*. Missing types aren't numpy compatible, and so much of the codebase is casting an option type to non-option, doing stuff, then casting back.
- Not compatible with numba.

Because of these reasons, I'd like to switch to using numpy arrays to hold the aggregates. This will play better with existing tools and simplifies our internals greatly. Aggregates actually are computed as numpy arrays, and are only cast to dynd arrays at the end, so this will only touch a few files anyway.

The big question then is how to handle missingness. I see a few options:

1. All missing types are floats, `nan` indicates missingness. This is by far the easiest method, but also seems a bit of a hack. Some quantities are inherently integers, forcing floating representation means loss of precision (although the importance of this is probably negligible here).
2. Subclass `ndarray`, and build a (limited) ndarray class that supports missingness with the same semantics as dynd. This may or may not be tricky, but will definitely be trickier than option 1.
3. No subclassing, store data in `Aggregate` classes as raw numpy arrays and a missingness flag (i.e. what value in the array indicates missingess). All operations go through this. This is similar to how the aggregates currently work, but would avoid all of the mucking with dynd.
4. Use numpy's own masked arrays. These are basically 2 arrays, one of data, and a boolean "mask". Pros: already supports many operations. Cons: increased storage cost (probably not important), not all things support them, abstraction sometimes leaks resulting in non-masked arrays. Note that option 2 would have this same issue as well, subclassing arrays robustly is difficult.
5. Keep dynd, and keep working around issues until it gets more featureful. Unsure of when that will happen, but they're making good progress.

Of these options, I'm leaning towards 1 or 4. Not sure what's best here.

---

A follow-up question is, if/once dynd is gone, do we continue to use datashape/odo? Datashape was used because I started with both blaze and dynd, and they each use it. After nixing both of these as dependencies, it may no longer make sense to use it. However, the cost of continuing to use it is minimal, it's quick to convert numpy dtype -> datashape. It would just remove dependencies, and the need for a second type system other than numpy/pandas's.

**Comment by pzwang** [comment]
Option 4 seems to make the most sense, although it would be nice from a space efficiency perspective if you could support 3.

I would encourage keeping datashape.  Just because you're not using dynd/odo for the moment, doesn't mean that we won't use it in the future.  Looking forward, I believe that we will need to use odo, dynd, and dask, and therefore keeping datashape makes the most sense.

**Comment by jbednar** [comment]
I feel the same way about datashape/odo -- they are helpful for keeping this project in line with the Continuum ecosystem as it evolves, and there doesn't seem to be a big cost involved in continuing to use them.

I don't think option 2 is good; it basically means reimplementing something like option 4, from scratch.  Option 5 also seems too open-ended; it's very unclear how long 2 and 5 would take to become viable.

Option  4 seems better; the aggregate data structures should be much smaller than the data itself for most of our use cases, and so having a somewhat inefficient format should be ok.  I don't know what storage format it uses for the boolean mask, but I guess doubling the storage is the worst case.
I'd also be ok with option 1.

Only you could say how much work option 3 would take.
