### ISSUE TITLE
Docs plan

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#437]
It's time for datashader to have some real documentation.  The plan is to use much of the infrastructure from [holoviews.org](http://holoviews.org), but that will require some cleanup and simplification.  For now, we'll focus on organizing a set of notebooks so that they can form the content of a web site, with an eye to plugging that into the new infrastructure as it develops.

I've pasted a proposed re-organization of the examples/ directory into a website below, following the basic structure of holoviews.org.  Comments welcome!

```
#!/bin/sh

touch                               getting_started/1-Introduction.ipynb
git mv pipeline.ipynb               getting_started/2-Pipeline.ipynb
git mv holoviews_datashader.ipynb   getting_started/3-Interactivity.ipynb # plus bokeh material

git mv plotting_pitfalls.ipynb      user_guide/1-Plotting_pitfalls.ipynb
touch                               user_guide/2-Points.ipynb          # some material from nyc_taxi.ipynb, nyc_taxi-nongeo.ipynb, and holoviews_datashader.ipynb
git mv tseries.ipynb                user_guide/3-Timeseries.ipynb
git mv trajectory.ipynb             user_guide/4-Trajectories.ipynb
touch                               user_guide/5-Rasters.ipynb         # Some material from landsat.ipynb
touch                               user_guide/6-Networks.ipynb        # Some material from edge_bundling.ipynb
touch                               user_guide/7-Geography.ipynb  # some material from census-hv-dask.ipynb, geoviews
touch                               user_guide/8-Extending.ipynb      

git mv census.ipynb                 topics/   # Replace last plot with census-hv.ipynb
git mv census-hv-dask.ipynb         topics/gerrymandering.ipynb
git mv edge_bundling.ipynb          topics/uk_researchers.ipynb
git mv landsat.ipynb                topics/ 
git mv lidar.ipynb                  topics/   # Needs cleanup
git mv nyc_taxi.ipynb               topics/
git mv nyc_taxi-nongeo.ipynb        topics/   # Redo with HV ; merge with nyc_taxi.ipynb after simplifying?
git mv nyc_taxi-paramnb.ipynb       topics/param_dashboard.ipynb
git mv opensky.ipynb                topics/
git mv osm.ipynb                    topics/   # Commit uncleared nb?
git mv osm-1billion.ipynb           topics/
git mv packet_capture_graph.ipynb   topics/network_packets.ipynb
git mv solar.ipynb                  topics/

git rm legends.ipynb          # Not working; see Interactivity for replacement
git rm hover_layer.ipynb      # Not working; see Interactivity for replacement
git rm race_elevation.ipynb   # No clear results ; could come back to someday
git rm census-hv.ipynb        # Moved into census.ipynb
```

**Comment by jlstevens** [comment]
Looks good! 

Assuming all this will still live in ``examples/``, this structure looks like it conforms to the holoviews.org organization with both 'Getting Started' and 'User' guides (but no galleries just yet). 

Note that holoviews.org does not yet build the ``examples/topics`` notebooks for use on the website (and your proposed organization would introduce quite a few of these these notebooks). This means we should figure out how to organize and display ``topics`` on both holoviews.org and datashader.org so we can use common build infrastructure for both.

**Comment by jbednar** [comment]
Good point.  I guess they can also be put under demos/bokeh/, which *will* be built?  I don't really think they are demos, though, more of in-depth studies.

**Comment by jbednar** [comment]
As far as the infrastructure goes, is there anything we want to take from how scikit-learn or scikit-image do their documentation (as suggested by @ceball)?  They too have galleries, thumbnails, and both .rst and .ipynb versions of everything.  See e.g. [plot_edge_filter](http://scikit-image.org/docs/dev/auto_examples/edges/plot_edge_filter.html).  They seem to generate the notebooks from rst rather than the other way around: [notebook.py](https://github.com/scikit-learn/scikit-learn/blob/7a23b2493fbe094db2528114d75edc2e9739da17/doc/sphinxext/sphinx_gallery/notebook.py).

**Comment by hsparra** [comment]
Looks good to me. For topics, how would it be titled? Would the title contain something so that a user could identify which example to look at to see certain features used. For example, the UK researches uses Graphs (same with the Packet Capture example). Not that I have an idea for any such title yet.

**Comment by hsparra** [comment]
Regarding legends, are we able to do those with Datashader, Holoviews, or Bokeh? If so we should have an example (probably already do).

**Comment by jbednar** [comment]
> For topics, how would it be titled? 

Good question.  I think it should be titled with the domain area, e.g. Taxi Trips, Flights, etc.  But it does need to show somewhere what it illustrates.

> Regarding legends

Right now, categorical legends can be constructed by hand as described in https://anaconda.org/jbednar/holoviews_datashader/notebook .  Other legend support is minimal and mostly broken, and desperately needs attention.  I can do that if I ever have time, and more realistically I can help someone to do that, but so far we've been trying to do different things...

**Comment by ceball** [comment]
@jbednar, is there an issue about improving legend support? If so, maybe this issue could now be closed...

**Comment by jbednar** [comment]
Legends are more properly discussed in https://github.com/bokeh/datashader/issues/126 , so I'll close this.
