### ISSUE TITLE
Dependency issues with the environment.yml for example notebooks

### ISSUE THREAD

**Issue by tjvananne** [bokeh/datashader#438]
I think it is important that the examples within this repo as well as the `environment.yml` enable even the casual Python user to be able to quickly get up and running with the datashader / bokeh / holoviews stack. I followed the steps exactly as they appear within the examples directory's README and found a few "gotchas" that I wanted to document somewhere in case it helps anyone else. 

**TLDR: after setting up the "ds" env from the `environment.yml` file, reinstall bokeh and datashader so they aren't the development versions. Then the examples should work (or atleast that's what it took for me).**

## my environment
* Windows 10
* conda 4.3.21
* Python 3.6

## setting up example environment
I think there are some dependency issues with the "ds" environment that is created from the `environment.yml` file.

As of commit dd58a72ebff4da73bf8052ec699a927d7ef634d2 on 8/13/2017, the `environment.yml` file will install:
* bokeh 0.12.7dev16 (should be 0.12.6)
* datashader 0.6.0dev5 (should be 0.5.0)

## bokeh issue
The issue with the above bokeh version (`0.12.7dev16`) is that when you import holoviews and run this code:

    hv.notebook_extension('bokeh')

You receive this error: "`HoloViews bokeh backend could not be imported, ensure bokeh is installed.`"

Then if you open a command prompt (I'm on windows, unfortunately) and run an install of bokeh

    activate ds
    conda install bokeh

...you'll receive bokeh version `0.12.6` and the issue above no longer applies

## datashader issue

The next issue I ran into while running the examples was with datashader version `0.6.0dev5` from the `environment.yml` file.

When running this code from the "holoviews_datashader.ipynb" (not sure best way to link to code within a notebook)

    np.random.seed(1)
    points = hv.Points(np.random.multivariate_normal((0,0), [[0.1, 0.1], [0.1, 1.0]], (1000000,)),label="Points")
    paths = hv.Path([0.15*random_walk(100000) for i in range(10)],label="Paths")
    decimate(points) + datashade(points) + datashade(paths)

This raises an exception in datashader/core.py in the `bypixel()` function, specifically with the `source` argument. This version tests the `source` argument to make sure it is either a pandas or dask DataFrame, which it is not. I added a `print(type(source))` immediately before the exception to figure out what this `source` object actually was and it turns out to be a `holoviews.core.data.Dataset`.

running this in command prompt to re-install datashader solves the problem:

    activate ds
    conda install -c bokeh datashader

This installs version 0.5.0 of datashader which has a version of `bypixel()` that does **not** make sure the `source` argument is a pandas or dask DataFrame. Instead, it just makes sure the data is in "tabular form" or something along those lines.

**Comment by jbednar** [comment]
We're about to make a new datashader release, and I think these issues should go away when we do.

**Comment by jbcrail** [comment]
Unfortunately, graph examples, such as `packet_capture_graph.ipynb`, rely on the development version of datashader. Along with an upcoming holoviews release, the new datashader release mentioned by @jbednar will resolve the datashader-specific issue.

The bokeh release will be resolved with datashader 0.6.0 is released when we will update `environment.yml` to use the main `bokeh` channel as suggested.

**Comment by tjvananne** [comment]
Thanks @jbednar @jbcrail - looking forward to 0.6.0!

Feel free to close this issue if you guys would like, I just wanted this documented somewhere in case it helps someone who wants to test out the examples.
