### ISSUE TITLE
AttributeError: 'Dataset' object has no attribute 'dtypes'

### ISSUE THREAD

**Issue by patrafter1999** [bokeh/datashader#440]
Hi there,

I followed instructions to install datashader and examples. I get the following error from examples/plotting_pitfalls.ipynb when run in jupyter notebook 5.0.0. Any idea to fix this will be greatly appreciated.

Regards,

%output size=200
datashade(hv.Points(dist))

WARNING:root:dynamic_operation: Exception raised in callable 'dynamic_operation' of type 'function'.
Invoked as dynamic_operation(height=400, scale=1.0, width=400, x_range=None, y_range=None)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda/envs/ds/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    330                 pass
    331             else:
--> 332                 return printer(obj)
    333             # Finally look for special method names
    334             method = get_real_method(obj, self.print_method)

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in pprint_display(obj)
    257     if not ip.display_formatter.formatters['text/plain'].pprint:
    258         return None
--> 259     return display(obj, raw=True)
    260 
    261 

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in display(obj, raw, **kwargs)
    243     elif isinstance(obj, (HoloMap, DynamicMap)):
    244         with option_state(obj):
--> 245             html = map_display(obj)
    246     else:
    247         return repr(obj) if raw else IPython.display.display(obj, **kwargs)

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in wrapped(element)
    129         try:
    130             html = fn(element,
--> 131                       max_frames=OutputSettings.options['max_frames'])
    132 
    133             # Only want to add to the archive for one display hook...

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in map_display(vmap, max_frames)
    198         return None
    199 
--> 200     return render(vmap)
    201 
    202 

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/ipython/display_hooks.py in render(obj, **kwargs)
     59     if renderer.fig == 'pdf':
     60         renderer = renderer.instance(fig='png')
---> 61     return renderer.html(obj, **kwargs)
     62 
     63 

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/plotting/renderer.py in html(self, obj, fmt, css, comm, **kwargs)
    253         code to initialize a Comm, if the plot supplies one.
    254         """
--> 255         plot, fmt =  self._validate(obj, fmt)
    256         figdata, _ = self(plot, fmt, **kwargs)
    257         if css is None: css = self.css

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/plotting/renderer.py in _validate(self, obj, fmt)
    189         if isinstance(obj, tuple(self.widgets.values())):
    190             return obj, 'html'
--> 191         plot = self.get_plot(obj, renderer=self)
    192 
    193         fig_formats = self.mode_formats['fig'][self.mode]

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/plotting/renderer.py in get_plot(self_or_cls, obj, renderer)
    164         """
    165         # Initialize DynamicMaps with first data item
--> 166         initialize_dynamic(obj)
    167 
    168         if not isinstance(obj, Plot) and not displayable(obj):

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/plotting/util.py in initialize_dynamic(obj)
    174             continue
    175         if not len(dmap):
--> 176             dmap[dmap._initial_key()]
    177 
    178 

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/core/spaces.py in __getitem__(self, key)
   1008         # Not a cross product and nothing cached so compute element.
   1009         if cache is not None: return cache
-> 1010         val = self._execute_callback(*tuple_key)
   1011         if data_slice:
   1012             val = self._dataslice(val, data_slice)

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/core/spaces.py in _execute_callback(self, *args)
    844 
    845         with dynamicmap_memoization(self.callback, self.streams):
--> 846             retval = self.callback(*args, **kwargs)
    847         return self._style(retval)
    848 

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/core/spaces.py in __call__(self, *args, **kwargs)
    518 
    519         try:
--> 520             ret = self.callable(*args, **kwargs)
    521         except:
    522             posstr = ', '.join(['%r' % el for el in self.args]) if self.args else ''

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/util/__init__.py in dynamic_operation(*key, **kwargs)
    341                 self.p.kwargs.update(kwargs)
    342                 obj = map_obj[key] if isinstance(map_obj, HoloMap) else map_obj
--> 343                 return self._process(obj, key)
    344         else:
    345             def dynamic_operation(*key, **kwargs):

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/util/__init__.py in _process(self, element, key)
    327             kwargs = {k: v for k, v in self.p.kwargs.items()
    328                       if k in self.p.operation.params()}
--> 329             return self.p.operation.process_element(element, key, **kwargs)
    330         else:
    331             return self.p.operation(element, **self.p.kwargs)

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/core/operation.py in process_element(self, element, key, **params)
    119         """
    120         self.p = param.ParamOverrides(self, params)
--> 121         return self._process(element, key)
    122 
    123 

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/operation/datashader.py in _process(self, element, key)
    466 
    467     def _process(self, element, key=None):
--> 468         agg = aggregate._process(self, element, key)
    469         shaded = shade._process(self, agg, key)
    470         return shaded

~/anaconda/envs/ds/lib/python3.6/site-packages/holoviews/operation/datashader.py in _process(self, element, key)
    320                       datatype=['xarray'], vdims=vdims)
    321 
--> 322         agg = getattr(cvs, glyph)(data, x, y, self.p.aggregator)
    323         if agg.ndim == 2:
    324             # Replacing x and y coordinates to avoid numerical precision issues

~/anaconda/envs/ds/lib/python3.6/site-packages/datashader-0.6.0.dev5-py3.6.egg/datashader/core.py in points(self, source, x, y, agg)
    174         if agg is None:
    175             agg = count()
--> 176         return bypixel(source, self, Point(x, y), agg)
    177 
    178     def line(self, source, x, y, agg=None):

~/anaconda/envs/ds/lib/python3.6/site-packages/datashader-0.6.0.dev5-py3.6.egg/datashader/core.py in bypixel(source, canvas, glyph, agg)
    373     # by only retaining the necessary columns:
    374     # https://github.com/bokeh/datashader/issues/396
--> 375     if categorical_in_dtypes(source.dtypes.values):
    376         # Preserve column ordering without duplicates
    377         cols_to_keep = OrderedDict({col: False for col in source.columns})

AttributeError: 'Dataset' object has no attribute 'dtypes'

:DynamicMap   []

**Comment by jbcrail** [comment]
@patrafter1999 A recent performance improvement to datashader caused a mismatch between datashader and holoviews (which depends on datashader). The error will be resolved by an upcoming holoviews release in the next day.
