### ISSUE TITLE
AttributeError: 'module' object has no attribute 'shade'

### ISSUE THREAD

**Issue by IreneCrisologo** [bokeh/datashader#444]
I just installed datashader using conda and was trying to follow the first example [here](http://datashader.readthedocs.io/en/latest/#).

The line ` img = tf.shade(agg, cmap=['lightblue', 'darkblue'], how='log') ` return the ff error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-9-69e3c892a795> in <module>()
----> 1 img = tf.shade(agg, cmap=['lightblue', 'darkblue'], how='log')

AttributeError: 'module' object has no attribute 'shade'
```

The version it installed is `'0.3.0'`

**Comment by jbednar** [comment]
0.3.0 is very old. You should get 0.5.0 if you ``conda install -c bokeh datashader``.  0.6.0 is due out later today or maybe Monday if we get stuck, so you'll probably want to upgrade again on Monday or Tuesday.
