### ISSUE TITLE
Errors in notebook examples

### ISSUE THREAD

**Issue by jbcrail** [bokeh/datashader#448]
I ran through the examples on the master branch and encountered a few errors. I have an upcoming PR to fix some.

Need to fix:
- [x] `census-hv-dask.ipynb`
- [x] `nyc_taxi.ipynb`
- [x] `osm.ipynb`
- [x] `osm-1billion.ipynb`
- [x] `packet_capture_graph.ipynb`
- [x] `race_elevation.ipynb`
- [x] `tseries.ipynb`

Untested due to large dataset size:
- `opensky.ipynb`

Skipped for now due to multiple errors:
- `landsat.ipynb`

**Comment by jbednar** [comment]
osm-1billion.ipynb can be tested easily; the dataset size is not too large, and it can be downloaded as specified in the notebook.  The changes needed can then be applied to osm.ipynb where appropriate.

**Comment by jbcrail** [comment]
@jbednar I downloaded and tested both osm notebooks successfully.
