### ISSUE TITLE
Downsampling a 2D (numpy) array 

### ISSUE THREAD

**Issue by nleclercq** [bokeh/datashader#462]
@jbednar

Hi James, 

I'm finally back with my question. I have a bokeh app - running in a jupyter notebook - that have to display several 'big' images - typically 1K x 1K pixels each. For performances reasons, I recently implemented a downsampling mechanism  using [skimage.transform.rescale](http://scikit-image.org/docs/dev/api/skimage.transform.html?highlight=rescale#skimage.transform.rescale). This approach works quite well but I'm wondering if datashader could do the job better than scikit-image does. 

Scikit-Image.rescale is literally a one line of code solution: `img_out = skimage.transform.rescale(img_in)` - where  `img_in/out` are numpy 2D arrays. Does datashader provides the same kind of feature? 

Thanks.

**Comment by jbednar** [comment]
I'm not sure precisely what the question is, but older versions of datashader used skimage to downsample images, and we've moved to code that we generally find to be faster based on the external "gridtools" project, working with xarray data.  @philippjfr, do we have a simple example of doing such regridding anywhere now?

**Comment by nleclercq** [comment]
Sorry for not being clear. 

My question was: does datashader provides something as simple as `img_out = rescale_2d_array(img_in)`?

**Comment by philippjfr** [comment]
Thanks for adding that here. I just realized that it doesn't auto-range and therefore errors if you don't supply an ``x_range`` and ``y_range``. @jbednar Should I open an issue for that?

**Comment by lnunno** [comment]
@philippjfr @nleclercq I'm interested in doing something similar. Namely, using datashader to only downsample a given dataframe based on image sizes. Is there an approach that would work with datashader 0.4.0 - the one that is currently packaged in Anaconda, or is upgrading strictly necessary? If there's something in the 0.4.0 API that could be used to that effect I'd be interested also.
