### ISSUE TITLE
packet capture example data indexing bug

### ISSUE THREAD

**Issue by philippjfr** [bokeh/datashader#469]
The maccdc2012_full_edges.parq data contains an index, which consists of string types. Since the edges are sorted by the index and strings do not sort numerically the returned paths are not in the correct order. The maccdc2012_full_edges.parq dataset should either contain an integer index or no index at all (which means pandas will default to integer indexing).

**Comment by jbednar** [comment]
I agree; no index is probably best. Definitely don't want any object dtypes, in any case!
