### ISSUE TITLE
Bundling slower and more jagged in recent commits

### ISSUE THREAD

**Issue by philippjfr** [bokeh/datashader#481]
One of these three commits introduced some weirdness in the edge bundling:

https://github.com/bokeh/datashader/pull/480
https://github.com/bokeh/datashader/pull/473
https://github.com/bokeh/datashader/pull/472

Visually comparing the bundling, you can see that it was smooth before:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/30828205-d24afd7a-a234-11e7-831f-08fd116ef47b.png)

And is quite jagged now:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/30828135-8c08a664-a234-11e7-8eac-058c48a038d5.png)

Additionally it is quite a bit slower:

PRE: CPU times: user 54.3 s, sys: 4.1 s, total: 58.4 s
POST: CPU times: user 2min 24s, sys: 8.41 s, total: 2min 33s

Here I'm comparing 400e9f00d9a08cca8916df7294dc19d964ecb3e2 (PRE) to https://github.com/bokeh/datashader/pull/480 (POST)

**Comment by jbcrail** [comment]
@philippjfr, thanks for narrowing this down. After rebasing the commits on a separate branch, I narrowed the issue down to PR #458 and #480. I'm still investigating.

**Comment by jbcrail** [comment]
I found the source of the jaggedness. It was the same issue found in the segfault issue (#477).
