### ISSUE TITLE
Error with example Holoviews_datashader

### ISSUE THREAD

**Issue by nachojov** [bokeh/datashader#489]
Hi all,
To get used and Learn Datashader from scratch I am trying to run some examples on my laptop. I decided to try first holoviews_datashader and when I run the cell at this point:

decimate(points) + datashade(points) + datashade(paths)

I got this error:

Expected `cmap` of `matplotlib.colors.Colormap` or `list`, got: '<class 'str'>'

Can you help me? I am running Python Anaconda 3.6.0, Bokeh 0.12.3, and 0.4.0 Datashader...Holoviews version is 1.8.4.

Thank you very much for your help

**Comment by philippjfr** [comment]
Could you try upgrading to datashader >=0.6.0? Try installing it with:

``conda install -c bokeh datashader``

**Comment by nachojov** [comment]
Thanks! Did it...however, I have this other error when I run the cell decimate(points) + datashade(points) + datashade(paths):

c:\anaconda\lib\site-packages\holoviews\plotting\bokeh\callbacks.py in set_customjs_callback(self, js_callback, handle)
    313         elif self.on_changes:
    314             for change in self.on_changes:
--> 315                 handle.js_on_change(change, js_callback)
    316         elif hasattr(handle, 'callback'):
    317             handle.callback = js_callback

AttributeError: 'Range1d' object has no attribute 'js_on_change'

¿Any idea? (Datashader version is 0.6.1 right now). 

Thanks again

**Comment by philippjfr** [comment]
Ha, sorry I should have spotted your bokeh version too. Try upgrading to 0.12.9 with:

``conda install -c bokeh bokeh=0.12.9``

**Comment by nachojov** [comment]
Yep!! It works!! 

Thank you for your help
