### ISSUE TITLE
InteractiveImage is broken with bokeh 0.12.10

### ISSUE THREAD

**Issue by kgullikson88** [bokeh/datashader#503]
I just upgraded to `bokeh=0.12.10`, and I can no longer import `InteractiveImage`:

    In [1]: from datashader.bokeh_ext import InteractiveImage
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-5ff0129ce74d> in <module>()
    ----> 1 from datashader.bokeh_ext import InteractiveImage
    
    ~/miniconda3/envs/datashader_test/lib/python3.6/site-packages/datashader/bokeh_ext.py in <module>()
          6 import numpy as np
          7
    ----> 8 from bokeh.io import notebook_div
          9 from bokeh.document import Document
         10 from bokeh.models import (CustomJS, ColumnDataSource, Square, HoverTool,
    
    ImportError: cannot import name 'notebook_div'

If I downgrade back to `bokeh=0.12.9`, the import works.

**Comment by philippjfr** [comment]
This was just fixed in https://github.com/bokeh/datashader/pull/502. There will be a datashader 0.6.2 very soon.

**Comment by kgullikson88** [comment]
Oh, cool! Thanks for the quick work.
