### ISSUE TITLE
Potential incompatibility issue with dask 0.16

### ISSUE THREAD

**Issue by philippjfr** [bokeh/datashader#529]
According to at least one user report there are now issues with using datashader with dask 0.16 due to a deprecation of a private method on the dask dataframe.

```
~/miniconda/envs/***/lib/python3.6/site-packages/dask/dataframe/core.py in __getattr__(self, key)
   2223             return new_dd_object(merge(self.dask, dsk), name,
   2224                                  meta, self.divisions)
-> 2225         raise AttributeError("'DataFrame' object has no attribute %r" % key)
   2226 
   2227     def __dir__(self):
AttributeError: 'DataFrame' object has no attribute '_default_get'
```

It appears the ``_default_get`` was removed in this commit:

https://github.com/dask/dask/commit/9e9fa10ef11bfe86a52214d8a2cda19508a4ee37#diff-492da7893fa5fa6ad3a6ef6cdef985f2

**Comment by apiszcz** [comment]
I am seeing the same problem.

**Comment by apiszcz** [comment]
This is good to know, I thought it was me, going back to 0.15.1

  File "lib\_sda\sda.py", line 394, in density
    agg=cvs.points(df, '_x', '_y', ds.count('_t'))
  File "C:\g\TEST_CODE\lib\datashader\core.py", line 175, in points
    return bypixel(source, self, Point(x, y), agg)
  File "C:\g\TEST_CODE\lib\datashader\core.py", line 419, in bypixel
    return bypixel.pipeline(source, schema, canvas, glyph, agg)
  File "C:\g\TEST_CODE\lib\datashader\utils.py", line 40, in __call__
    return lk[typ](head, *rest, **kwargs)
  File "C:\g\TEST_CODE\lib\datashader\dask.py", line 21, in dask_pipeline
    get = _globals['get'] or df._default_get
  File "C:\g\TEST_CODE\lib\dask\dataframe\core.py", line 2225, in
__getattr__
    raise AttributeError("'DataFrame' object has no attribute %r" % key)
AttributeError: 'DataFrame' object has no attribute '_default_get'.
