### ISSUE TITLE
Installed using Conda , unable to run : "SystemError: Parent module '' not loaded, cannot perform relative import"

### ISSUE THREAD

**Issue by kfedotov-fulcrm** [bokeh/datashader#532]
Installed using conda install -c bokeh datashader

conda list returns:
bokeh                     0.12.4                   py35_0
...
datashader                0.5.0                    py35_0    bokeh
...

Primarily using jupyter but this error occurs in python3.5 from shell as well:
>>> import math
>>> import numpy as np
>>> import pandas as pd
>>> import holoviews as hv
>>> import fastparquet as fp
>>> import datashader as ds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.5/site-packages/datashader/__init__.py", line 5, in <module>
    from .core import Canvas
  File "/opt/anaconda3/lib/python3.5/site-packages/datashader/core.py", line 5, in <module>
    from odo import discover
  File "/opt/anaconda3/lib/python3.5/site-packages/odo/__init__.py", line 12, in <module>
    from .convert import convert
  File "/opt/anaconda3/lib/python3.5/site-packages/odo/convert.py", line 10, in <module>
    from .core import NetworkDispatcher, ooc_types
  File "/opt/anaconda3/lib/python3.5/site-packages/odo/core.py", line 6, in <module>
    import networkx as nx
  File "/opt/anaconda3/lib/python3.5/site-packages/networkx/__init__.py", line 74, in <module>
    from networkx import release
  File "/opt/anaconda3/lib/python3.5/site-packages/networkx/release.py", line 225, in <module>
    date, date_info, version, version_info, vcs_info = get_info()
  File "/opt/anaconda3/lib/python3.5/site-packages/networkx/release.py", line 157, in get_info
    from version import date, date_info, version, version_info, vcs_info
  File "param/version.py", line 83, in init param.version (param/version.c:7001)
    import os, subprocess
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by jbednar** [comment]
Those are very old versions; you probably need to do "conda update conda" in your root conda environment to get the right versions (new conda versions look in different places for packages than the old ones did, so old conda versions will keep trying to install old packages).

**Comment by kfedotov-fulcrm** [comment]
Hmm seems like I am at the latest version:
 conda update conda
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /opt/anaconda3:
#
conda                     4.3.30           py35hf9359ed_0

I am considering doing the git install method for datashader, but would rather not install an unreleased version if possible

**Comment by jbednar** [comment]
As it happens, datashader 0.6.3 was released earlier today, and so there's nothing unreleased about git master at this moment!  But you're getting datashader 0.5.0, which is four releases back, and bokeh 0.12.4, which is seven releases back.  

You do indeed the latest version of conda, and also the same version I have, so something is amiss! Maybe try ``conda install -c bokeh datashader=0.6.3 bokeh=0.12.11``, and report what that tells you?  And say what platform you're using?

**Comment by kfedotov-fulcrm** [comment]
yea this taking me for an upgrade loop it seems

`conda install -c bokeh datashader=0.6.3 bokeh=0.12.11
Fetching package metadata .............
Solving package specifications: .
UnsatisfiableError: The following specifications were found to be in conflict:
  - datashader 0.6.3* -> param >=1.5.0,<2.0
  - lancet -> param 1.3.2
Use "conda info <package>" to see the dependencies for each package`

I was able to install bokeh 0.12.11 on its own 

`conda install -c bokeh bokeh=0.12.11            Fetching package metadata .............
Solving package specifications: .
Package plan for installation in environment /opt/anaconda3:
The following packages will be UPDATED:
    bokeh:      0.12.4-py35_0 --> 0.12.11-py_0 bokeh
    datashader: 0.4.0-py35_0  --> 0.5.0-py35_0 bokeh
Proceed ([y]/n)? y

bokeh-0.12.11- 100% |#############################################################| Time: 0:00:00  29.81 MB/s`

Which didn't quite fix the problem but did downgrade? bokeh and upgraded datashader

`conda list | grep datashader
datashader                0.5.0                    py35_0    bokeh
`

The error remains the same though both jupyter and cmd. This running off ubuntu 14.04

**Comment by jbednar** [comment]
Oh, shoot!  The dependency on lancet shouldn't be there; we need to track that down and get rid of that!  For now, ``conda install -c bokeh -c ioam bokeh datashader`` might fix it, but we really need to fix something if lancet is in the dependency chain.

**Comment by kfedotov-fulcrm** [comment]
Oh ok , so I shouldn't worry about lancet then..
But this for some reason didn't update, still remains at the same version, same error on execution

```
conda install -c bokeh -c ioam bokeh datashader
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /opt/anaconda3:
#
bokeh                     0.12.11                    py_0    bokeh
datashader                0.5.0                    py35_0    bokeh

```

**Comment by jbednar** [comment]
Sigh.  I don't suppose ``conda install -c bokeh -c ioam datashader=0.6.3 bokeh=0.12.11`` would do it?

**Comment by kfedotov-fulcrm** [comment]
Looks like it may be solved in a hacky way:


Running that command this just added biggus to the list of dependencies it seems.
```
conda install -c bokeh -c ioam datashader=0.6.3 bokeh=0.12.11
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - biggus
  - datashader 0.6.3*
  - lancet
Use "conda info <package>" to see the dependencies for each package.
```

wilder still, is the github method did not install datashader but simply updated param to 1.5.1

```
conda remove --force datashader
git clone https://github.com/bokeh/datashader.git
Cloning into 'datashader'...
remote: Counting objects: 4850, done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 4850 (delta 103), reused 123 (delta 63), pack-reused 4664
Receiving objects: 100% (4850/4850), 20.42 MiB | 10.83 MiB/s, done.
Resolving deltas: 100% (3270/3270), done.
Checking connectivity... done.
cd datashader/
pip install -e .
Obtaining file:///root/datashader
Requirement already satisfied: dask>=0.15.4 in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Requirement already satisfied: datashape>=0.5.1 in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Requirement already satisfied: numba>=0.35.0 in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Requirement already satisfied: numpy>=1.7 in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Requirement already satisfied: pandas>=0.15.0 in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Requirement already satisfied: pillow in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Requirement already satisfied: xarray>=0.9.6 in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Requirement already satisfied: colorcet in /opt/anaconda3/lib/python3.5/site-packages (from datashader==0.6.3)
Collecting param<2.0,>=1.5.0 (from datashader==0.6.3)
  Downloading param-1.5.1.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 4.6MB/s
Requirement already satisfied: multipledispatch>=0.4.7 in /opt/anaconda3/lib/python3.5/site-packages (from datashape>=0.5.1->datashader==0.6.3)
Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.5/site-packages (from datashape>=0.5.1->datashader==0.6.3)
Requirement already satisfied: llvmlite in /opt/anaconda3/lib/python3.5/site-packages (from numba>=0.35.0->datashader==0.6.3)
Requirement already satisfied: pytz>=2011k in /opt/anaconda3/lib/python3.5/site-packages (from pandas>=0.15.0->datashader==0.6.3)
Requirement already satisfied: olefile in /opt/anaconda3/lib/python3.5/site-packages (from pillow->datashader==0.6.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.5/site-packages (from python-dateutil->datashape>=0.5.1->datashader==0.6.3)
Building wheels for collected packages: param
  Running setup.py bdist_wheel for param ... done
  Stored in directory: /root/.cache/pip/wheels/aa/51/fc/ed1439a6a5d840c935691d8224e9092d4c0339055a7641d82f
Successfully built param
Installing collected packages: param, datashader
  Found existing installation: param 1.4.1
    Uninstalling param-1.4.1:
      Successfully uninstalled param-1.4.1
  Running setup.py develop for datashader
Successfully installed datashader param-1.5.1
```

So I reran that again:

```
pip install -e .
...
...
...
Installing collected packages: datashader
  Found existing installation: datashader 0.6.3
    Uninstalling datashader-0.6.3:
      Successfully uninstalled datashader-0.6.3
  Running setup.py develop for datashader
Successfully installed datashader
conda list | grep datashader

```
Doesn't come up in conda list and now the error is 

```
>>> import datashader as ds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'datashader'
```

So what I did was move the ~/datashader/datashader dir directly into /opt/anaconda/lib/python3.5/site-packages/
Updated holoviews 
`conda install holoviews`

And that seems to have fixed all the import issues. I guess I made the package un-updatable through conda this way though.
I think we close this specific issue ,although you seem to be the right person to ask about the next issue that came up trying to run the edge_bundling example from your notebook. Where would be a good place to ask for directions with this error?
```
client=Client()
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
... ... ...
```
Thank you

**Comment by jbednar** [comment]
The best we can figure is that you had previously installed holoviews via conda-forge, which had a completely bogus dependency on lancet listed for historical reasons I understand now but which are too complex to go into.  We've opened a PR to remove that dependency: https://github.com/conda-forge/holoviews-feedstock/pull/19

It was surprising that Lancet would cause any dependency  conflicts in the first place; it's a pure-Python library with only one dependency (on Param, which itself has no dependencies).  But it turns out that it was last released during a time in which noarch packages were not fully supported by conda, and instead it has binary releases only for certain Python versions that were popular at the time.  We can fix that by updating Lancet to be a noarch package.

It sounds like you have things working now, but if you want to see if you can get a conda-based version working now, you can try uninstalling holoviews and re-installing it using ``conda install -c ioam holoviews``, to avoid having the bogus Lancet dependency.  Meanwhile, hopefully the new conda-forge recipe will get merged soon, so that the conda-forge and ioam versions of HoloViews become the same as they should be.

Dependency hell!!

As for the tornado issue, please file that on the HoloViews repo if it's happening in a cell with HoloViews objects, or on the datashader repo if it's in a pure-bokeh visualization.  Do make sure you have bokeh 0.12.11 (the current version) before investigating that, though.

**Comment by kfedotov-fulcrm** [comment]
If you are having dependency issues, I might as well give up!
Thanks again for the help
