### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by rmania** [bokeh/datashader#534]
I installed datashader from my anaconda prompt as such:
`conda install -c bokeh datashader`

it installed the module correctly in the dir: C:\Users\my_name\Lib\site-packages

(Note that I previsouly installed bokeh version '0.12.11' which is correctly running) 

When i run 
`import datashader as ds `
in jupyter notebook, I get this error:
I removed and reinstalled plenty of times but I can't seem to fix this:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-236dc39df287> in <module>()
----> 1 import datashader as ds

C:\Users\Diederik\lib\site-packages\datashader\__init__.py in <module>()
      7                          mean, std, var, count_cat, summary)
      8 from .glyphs import Point                                # noqa (API import)
----> 9 from .pipeline import Pipeline                           # noqa (API import)
     10 from . import transfer_functions as tf                   # noqa (API import)
     11 

C:\Users\Diederik\lib\site-packages\datashader\pipeline.py in <module>()
      3 from toolz import identity
      4 
----> 5 from . import transfer_functions as tf
      6 from . import reductions
      7 from . import core

C:\Users\Diederik\lib\site-packages\datashader\transfer_functions.py in <module>()
      8 import toolz as tz
      9 import xarray as xr
---> 10 from PIL.Image import fromarray
     11 
     12 

C:\Users\Diederik\lib\site-packages\PIL\Image.py in <module>()
     54     # Also note that Image.core is not a publicly documented interface,
     55     # and should be considered private and subject to change.
---> 56     from . import _imaging as core
     57     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     58         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: Kan opgegeven module niet vinden.
```

**Comment by jbednar** [comment]
This issue has been very confusing, but it looks like there are some [issues with pillow versions for Windows](https://stackoverflow.com/questions/43264773/pil-dll-load-failed-specified-procedure-could-not-be-found).  I really can't tell what's going on, given that the versions we are using don't clearly match the ones listed there, but the symptoms are definitely the same.  For now, we're just going to pin pillow at version 4.0.0, the last one we are sure was working.  You can try that yourself (``conda install -c conda-forge pillow=4.0.0``), and we'll also prepare a new datashader release with the same constraint if we can get everything passing.

**Comment by jbednar** [comment]
Should be fixed in datashader 0.6.4.

**Comment by rmania** [comment]
This solved some issues for now but I had to downgrade PIL to  4.0.0. thnx for now

**Comment by philippjfr** [comment]
Note the description above is not actually how we ended up solving it. The issue was that matplotlib has conflicts with pillow 4.3.0 on the main channel, so it forced a downgrade to pillow 4.2.1 which has that error. The matplotlib in conda-forge does not have the issue, and keeps pillow 4.3.0 installed. So I'd recommend installing matplotlib from conda-forge, which will let you stick with pillow 4.3.0.

**Comment by jbednar** [comment]
Still odd that 4.2.1 would have that error, if it was fixed in 4.1.1. Something still doesn't seem to add up...

**Comment by philippjfr** [comment]
Could be related to this?

>Windows users can install the OpenJPEG binaries available on the OpenJPEG website, but must add them to their PATH in order to use PIL (if you fail to do this, you will get errors about not being able to load the _imaging DLL).

Or it could be related to this: https://github.com/python-pillow/Pillow/issues/2688

**Comment by ek-nath** [comment]
Works for me on Windows 10, python 3.6.4 **if** I use `conda install -c conda-forge pillow=4.0.0`. I am using `datashader` version 0.6.4 though and had to downgrade `matplotlib` during the downgrade of `pillow`
