### ISSUE TITLE
Datashader import error when running NYC taxi example code

### ISSUE THREAD

**Issue by Gandoban** [bokeh/datashader#541]
I'm working through the Datashader NYC taxi example visualizaton code from the following URL:
https://bokeh.github.io/datashader-docs/topics/nyc_taxi.html
I'm doing this using Jupyter Nootebook (through Anaconda), and when I run the code for '10-million-point datashaded plots: interactive', I get the following error message (code first):

import datashader as ds
from datashader.bokeh_ext import InteractiveImage
from functools import partial
from datashader.utils import export_image
from datashader.colors import colormap_select, Greys9, Hot, inferno

background = "black"
export = partial(export_image, export_path="export", background=background)
cm = partial(colormap_select, reverse=(background=="black"))

def create_image(x_range, y_range, w=plot_width, h=plot_height):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.points(df, 'dropoff_x', 'dropoff_y',  ds.count('passenger_count'))
    img = tf.shade(agg, cmap=Hot, how='eq_hist')
    return tf.dynspread(img, threshold=0.5, max_px=4)

p = base_plot(background_fill_color=background)
export(create_image(*NYC),"NYCT_hot")
InteractiveImage(p, create_image)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-17-fe080dac7905> in <module>()
      1 import datashader as ds
----> 2 from datashader.bokeh_ext import InteractiveImage
      3 from functools import partial
      4 from datashader.utils import export_image
      5 from datashader.colors import colormap_select, Greys9, Hot, viridis, inferno

C:\ProgramData\Anaconda3\lib\site-packages\datashader\bokeh_ext.py in <module>()
     23 if bokeh_version > '0.12.9':
     24     from bokeh.protocol import Protocol
---> 25     from bokeh.embed import notebook_content
     26     from bokeh.embed.notebook import encode_utf8
     27     from bokeh.io.notebook import CommsHandle, get_comms

ImportError: cannot import name 'notebook_content'

I'm puzzled, because this is the example code, unedited, so I'm not sure why it wouldn't work. I'm running Python 3.6 on Windows 10 and I've updated Datashader (and Bokeh) to the latest version. Has anyone else encountered this problem or know what might be causing it?

Thanks in advance for your time.

**Comment by jbednar** [comment]
That is due to a change in bokeh, and the latest release of datashader, 0.6.4, should have the updated call instead. Are you sure you have datashader 0.6.4, from "conda install -c bokeh datashader"?

**Comment by Gandoban** [comment]
I've chacked and I realised that I updated Datashader in a different environment ... (blushes). I updated it in teh environment I was actually working with and everything's working now. Thanks for your help.

**Comment by jbednar** [comment]
No problem.  I can't even count how many times I've sworn to my co-workers that things were broken on the very latest revision of master, eventually finding out I was on some stray branch instead... :-)
