### ISSUE TITLE
heatmap with 21k points using datashader

### ISSUE THREAD

**Issue by LarryMartell** [bokeh/datashader#548]
Posted question here: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/RSTuOTDA9MU

Pasted my code below. The 1D to 2D Conversion came from JS code I got from plotly that I converted to python.  My data is at https://larrymartell.github.io/dt.js.

I've attached a plotly heatmap that is the format I want. This only has 9 points but it's an example of the style. Thank so much for looking at this!

![screen shot 2017-12-18 at 11 59 59 am](https://user-images.githubusercontent.com/1308192/34117781-b93d0b8c-e3ea-11e7-9a0b-f55dbdcb3a31.png)

```

import math

import numpy as np
import holoviews as hv
from data_l import data
hv.notebook_extension('matplotlib')
try:
    from skimage.exposure import equalize_hist
    eq_hist = lambda d, m: equalize_hist(1000 * d, nbins=100000, mask=m)
except ImportError:
    eq_hist = lambda d, m: d
    print("scikit-image not installed; skipping histogram equalization")

""" 1d TO 2D Conversion Start """
# Create 2D data based on:
# https://github.com/plotly/plotly.js/blob/master/src/traces/heatmap/convert_column_xyz.js

roundingError = 1e-9
BADNUM = None


x = data['x']
y = data['y']
z = data['z']


def lessThan(a, b):
    return a < b


def lessOrEqual(a, b):
    return a <= b


def greaterThan(a, b):
    return a > b


def greaterOrEqual(a, b):
    return a >= b


def init2dArray(rowLength, colLength):
    array = [5] * rowLength
    for i in range(rowLength):
        array[i] = [5] * colLength
    return array


def sorterAsc(a, b):
    return a - b


def distinctVals(valsIn):
    vals = valsIn[:]  # otherwise we sort the original array...
    vals.sort()
    le = len(vals) - 1
    minDiff = (vals[le] - vals[0]) or 1
    errDiff = minDiff / (le or 1) / 10000
    v2 = [vals[0]]
    for i in range(le):
        # make sure values aren't just off by a rounding error
        if(vals[i + 1] > vals[i] + errDiff):
            minDiff = min(minDiff, vals[i + 1] - vals[i])
            v2.append(vals[i + 1])
    return {'vals': v2, 'minDiff': minDiff}


def findBin(val, bins, linelow=None):
    n1 = 0
    n2 = len(bins)
    c = 0
    binSize = 1
    if n2 > 1:
        binSize = (bins[n2 - 1] - bins[0]) / (n2 - 1)
    n = test = None
    if(binSize >= 0):
        if linelow:
            test = lessThan
        else:
            test = lessOrEqual
    else:
        if linelow:
            test = greaterOrEqual
        else:
            test = greaterThan

    if linelow == -1:
        linelow = 1
    if binSize >= 0:
        linelow = 1
    else:
        binSize = -1

    val += binSize * roundingError * linelow * binSize
    while (n1 < n2 and c < 100):
        c += 1
        n = math.floor((n1 + n2) / 2)
        if test(bins[int(n)], val):
            n1 = n + 1
        else:
            n2 = n
    if(c > 90):
        print ('Long binary search...')
    return n1 - 1


var1Name = 'x'
var2Name = 'y'
arrayVarNames = ['z']
col1 = x
col2 = y
colLen = min(len(col1), len(col2))
arrayVar = z
if(arrayVar):
    colLen = min(colLen, len(arrayVar))
if(colLen < len(col1)):
    col1 = col1.slice(0, colLen)
if(colLen < len(col2)):
    col2 = col2.slice(0, colLen)
col1dv = distinctVals(col1)
col1vals = col1dv['vals']
col2dv = distinctVals(col2)
col2vals = col2dv['vals']
newArrays = []
for i in range(len(arrayVarNames)):
    newArrays.append(init2dArray(len(col2vals), len(col1vals)))

i1 = None
i2 = None
for i in range(colLen):
    if(col1[i] != BADNUM and col2[i] != BADNUM):
        i1 = findBin(col1[i] + col1dv['minDiff'] / 2, col1vals)
        i2 = findBin(col2[i] + col2dv['minDiff'] / 2, col2vals)
        for j in range(len(arrayVarNames)):
            arrayVarName = arrayVarNames[j]
            newArray = newArrays[j]
            newArray[int(i2)][int(i1)] = arrayVar[i]

z = newArray
""" 1d TO 2D Convertion End """


def heatmap(offset=0.0, transform=lambda d, m: d, label=None):
    """
    Given a set of coordinates, bins them into a 2d histogram grid
    of the specified size, and optionally transforms the counts
    and/or compresses them into a visible range starting at a 
    specified offset between 0 and 1.0.
    """
    hist, xs, ys = np.histogram2d(x, y, bins=len(x))
    hist = np.array(z)
    counts = hist[:, ::-1].T
    transformed = transform(counts, counts != 0)
    span = transformed.max() - transformed.min()
    compressed = np.where(
        counts != 0, offset + (1.0 - offset) * transformed / span, 0)
    args = dict(label=label) if label else {}
    return hv.Image(compressed, bounds=(xs[-1], ys[-1], xs[1], ys[1]), **args)


img = hv.Layout(
    [heatmap(
        transform=eq_hist,
        label='rainbow'
    )(style=dict(cmap='rainbow', how='linear', background="white"))]
)
renderer = hv.Store.renderers['matplotlib'].instance(fig='png', holomap='gif')
renderer.save(img, 'datashader_test_image')

```

**Comment by jbednar** [comment]
I was able to run your code using the example dataset by removing "var " from the .js file to make it into Python and then replacing the import with ``exec(open("../../dt.py").read(), globals())`` to define ``data``.  That seemed to work, in that I did get a plot that was mostly violet:

![image](https://user-images.githubusercontent.com/1695496/34121074-6e388e06-e3ed-11e7-902a-8568962934c9.png)

But that's some seriously obscure, non-Pythonic code, and it would take me much more time than I'd be willing to invest in it to try to step through it and figure out what it does, either for the [plotly original](https://github.com/plotly/plotly.js/blob/master/src/traces/heatmap/convert_column_xyz.js) or the other code above.  Can you distill it down to just the output of whatever those steps above are meant to do, and then have some simple data structure along with the plot you get and how you were hoping to get a different plot?

**Comment by LarryMartell** [comment]
Yes, the all violet plot is what I get and is what the issue is. As I said on the mailing list, I think what is happening is that because most of the points have a 0 value that is the min and is colored with violet and even though there may be other colors in there the 440,979,000 violet points totally obscure the 21,000 points with other colors. Would you agree that is the case?

The obscure, non-Pythonic code was converted from the obscure JS code plotly sent me. What it does is convert data that has 3 1D lists, e.g. x = [1, 2, 3] y=[4,5,6] z=[7,8,9] (where Z is the value) into one list of lists where every point is represented. If a point has no value it get a null (or none or 0). So for this example we have 3 data points (1,4,7), (2,5,8), (3,6,9) - but plotly requires 18 points: 

[[1,1,0], [1,2,0], [1,3,0], [1,4,7], [1,5,0], [1,6,0],
 [2,1,0,],[2,2,0], [2,3,0], [2,4,0], [2,5,8], [2,6,0],
 [3,1,0], [3,2,0], [3,3,0], [3,4,0], [3,5,0], [3,6,9]]

The plotly heatmap code has some smoothing algorithm to transition and blend the colors from the 0 points to the non-zero points. With plotly you can pass in the 3 1D lists and it will do the conversation and smoothing, or you can pass in the 1 2D list and it will just do the smoothing. But it cannot handle my data set with 3 21k lists (and I cannot pass in the 2D list I create). 

Maybe I am thinking about this incorrectly for datashader. If I have 3 lists as I do, what is the best way to represent this data in a heatmap that approximates the look of the plotly one? 

On the page https://bokeh.github.io/datashader-docs/user_guide/1_Plotting_Pitfalls.html at the end you show what looks like a heatmap. Could something like that be used for my data to get what I want?

**Comment by philippjfr** [comment]
Is this what you want:

```python
import json
import holoviews as hv
import datashader as ds
from holoviews.operation.datashader import aggregate

hv.extension('matplotlib')

with open('/Users/philippjfr/Downloads/dt.js', 'r') as f:
    dtjs = json.load(f)

aggregate(hv.Scatter(dtjs, ['x', 'y'], 'z'), x_sampling=0.035,
          y_sampling=0.035, aggregator=ds.mean('z')).opts(plot=dict(colorbar=True))
```

There doesn't seem to be a whole lot of structure to the data though:

![image](https://user-images.githubusercontent.com/1550771/34126459-8b40b0a2-e431-11e7-9708-067cfbc6edd9.png)

**Comment by jbednar** [comment]
> Note: I had to edit the js file a bit to make it valid json, (i.e. take out var data = and a trailing comma).

Interesting; it took less editing to turn it into Python than into JSON! 

> most of the points have a 0 value that is the min and is colored with violet and even though there may be other colors in there the 440,979,000 violet points totally obscure the 21,000 points with other colors. Would you agree that is the case?

I still don't quite get the issue here; zero points shouldn't obscure other points, as long as the points have some distribution in x,y.  It would probably help if you thought about this process in terms of pixels (bins in the heatmap): points that fall into the same bin will be binned together; the rest will go somewhere else.  And note that the heatmap example from our docs is *not* doing any interpolation, like the plotly one seems to be; datashader won't synthesize some smoothed plot from scattered points, it just plots each point (in whatever pixel/bin) it falls.

For what it's worth, it's probably useful to look at your data without the 'z' values:

![image](https://user-images.githubusercontent.com/1695496/34127356-696075be-e402-11e7-820c-68fcc380beec.png)

**Comment by jbednar** [comment]
(And you should probably do this using the bokeh extension so that you can zoom in and explore each local region.)
