### ISSUE TITLE
documentation link to Landsat example notebook broken

### ISSUE THREAD

**Issue by rabernat** [bokeh/datashader#559]
Under the "interactivity" heading in this documentation page:
http://datashader.org/user_guide/5_Rasters.html

There is a link to the following url:
http://datashader.org/topics/Landsat.html

which returns a 403 forbidden error

**Comment by philippjfr** [comment]
Links should be all lowercase it seems: http://datashader.org/topics/landsat.html

**Comment by jbednar** [comment]
Thanks; should be fixed now!  I thought we had a link checker running, but it must only be making warnings during doc builds, not errors...
