### ISSUE TITLE
cannot import `connect_edges` on windows

### ISSUE THREAD

**Issue by BielStela** [bokeh/datashader#575]
I'm trying to reproduce the network example from the website but I cannot import `connect_edges`.

``` python
from datashader.bundling import connect_edges, hammer_bundle
```
```
ImportError: cannot import name 'connect_edges'
```

**Comment by jbednar** [comment]
Sounds like you have an old version.  Make sure you are using Datashader 0.6.5; bundling is a relatively recent addition.  You can get 0.6.5 by doing `conda install -c bokeh datashader`.

**Comment by BielStela** [comment]
Nice, that was the problem. Thanks!
