### ISSUE TITLE
Struggles with bay_trimesh.ipynb example

### ISSUE THREAD

**Issue by rsignell-usgs** [bokeh/datashader#581]
I was super excited to find out out the datashader capabilities with triangular grids, and saw the `bay_trimesh` notebook here:
http://datashader.org/topics/bay_trimesh.html
https://github.com/bokeh/datashader/blob/master/examples/topics/bay_trimesh.ipynb

The first issue, easy to fix, was that the data for this notebook did not get downloaded following the procedure here: 
https://github.com/bokeh/datashader/blob/master/examples/README.md
got the datasets.yml version packaged with conda which was jan 30, while the bay data was added feb 2 
in  https://github.com/bokeh/datashader/commits/master/examples/datasets.yml
I guess this will be fixed in the next release -- I just downloaded the new datasets.yml of course.

The 2nd issue is that when running the notebook, I'm getting this error in the holoviews sections:
```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-0f332066925a> in <module>()
      5 get_ipython().run_line_magic('opts', 'Image RGB [width=450 height=450]')
      6 
----> 7 datashade(hv.TriMesh((tris,verts), label="Wireframe")) + datashade(hv.TriMesh((tris,hv.Points(verts, vdims='z')), label="TriMesh"), aggregator=ds.mean('z'))

AttributeError: module 'holoviews' has no attribute 'TriMesh'
```
I found `hv.QuadMesh` and `hv.TriSurface`, but no `TriMesh`.  

Does the notebook need to be updated to match the lastest release?

**Comment by philippjfr** [comment]
@rsignell-usgs Unfortunately there has been no official HoloViews release which includes TriMesh yet, however, you can get the alpha version for now using:

```
conda install -c ioam/label/dev holoviews
```

The same thing will also work for GeoViews.

**Comment by rsignell-usgs** [comment]
@philippjfr , yes, it works!:

![2018-03-24_21-46-21](https://user-images.githubusercontent.com/1872600/37870846-8b150818-2fad-11e8-9d91-2c458e57353b.png)

It's really exciting to have this tri_mesh capability!  

We've been struggling with how do deliver dynamic WMS services for large (2-11M+ node) ocean model meshes, and it seems a nice solution would be to put GeoViews on the backend of [sci-wms](https://github.com/sci-wms/sci-wms)
