### ISSUE TITLE
Datashader + Bokeh callback not working in Jupyter Lab when using Holoviews layout

### ISSUE THREAD

**Issue by benvddriessche** [bokeh/datashader#583]
Plotting data in Holoviews + Datashader + Bokeh works fine both in Jupyter Notebook and Jupyter Lab **when** rendering a single plot with a single or multiple overlaid datasets.

However, when constructing a layout (e.g. `(datashade(x) + datashade(y)).cols(1)` ), Datashader no longer updates the plots correctly. It looks like the callback to update the image as a function of zoom level is no longer functional. This issue **only** occurs in Jupyter Lab.

I got Jupyter Lab to show Bokeh output in the first place with:

```
conda install -c bokeh/label/dev bokeh
conda install -c ioam/label/dev holoview
```

_Relevant conda packages:_
bokeh v0.12.15rc2
datashader v0.6.5
holoviews v1.10.0a2
jupyterlab v0.31.12

_Relevant Jupyter Lab extensions:_
pyviz/jupyterlab_holoviews v0.3.2
jupyterlab_bokeh v0.4.0

**Comment by philippjfr** [comment]
Opened the corresponding issue in holoviews and submitted a PR to fix it here: https://github.com/ioam/holoviews/pull/2511
