### ISSUE TITLE
Pip install datashader[examples] not yet possible

### ISSUE THREAD

**Issue by ceball** [bokeh/datashader#588]
(draft, will complete after #564)

While `pip install datashader` is now straightforward, `pip install datashader[examples]` is not.

Below are packages which currently require extra steps outside of pip. E.g. they may have unstated install/build time dependencies, depend on things that aren't on pypi, depend on having compiler, headers, and so on.

  * cartopy (https://github.com/SciTools/cartopy/issues/1035)
  * graphviz (depends on underlying graphviz lib)
  * fastparquet
  * geoviews (not on pypi)
  * iris
  * krb5
  * rasterio
  * pyproj
  * pytables
  * snappy (depends on underlying snappy lib)
  * shapely
  * statsmodels

Some of these are already easy to install on one or more platforms (e.g. binaries are available from somewhere). Over time, others may also become easier to install. As more wheels become available, more will be installable via pip. However, right now, it's probably too much work to explain how to install everything necessary on every platform.

`pip install datashader[examples_pip]` is the current best effort to install as many dependencies as possible.

**Comment by ceball** [comment]
Actually, cartopy has install-time dependencies beyond those two. I'll come back to this later.

**Comment by jbednar** [comment]
Ok, thanks.

**Comment by ceball** [comment]
This issue's now out of date (there's no datashader-examples package; the difficulties will instead move to (some topic of) pyviz...).
