### ISSUE TITLE
Resolve port collision in dashboard.py

### ISSUE THREAD

**Issue by brendancol** [bokeh/datashader#6]
- [ ] increment port if current port is not available
- [x] notify user of url to app

**Comment by brendancol** [comment]
I've put this one on hold until bokeh server team responds.

**Comment by jbednar** [comment]
Any response from them yet?  If not, can you ping them?

**Comment by brendancol** [comment]
at the moment, opting for keeping the port arg and not auto-incrementing port number upon collision
