### ISSUE TITLE
Release 0.6.6 on conda-forge

### ISSUE THREAD

**Issue by ceball** [bokeh/datashader#605]
I've updated the recipe but haven't yet made a PR (need to add pyct to c-f, plus check other dependencies).

https://github.com/conda-forge/datashader-feedstock/compare/master...ceball:release_v0.6.6?expand=1

Will also be able to close https://github.com/conda-forge/datashader-feedstock/issues/3

**Comment by ceball** [comment]
I've now made https://github.com/conda-forge/staged-recipes/pull/5980 to get pyct onto c-f.

**Comment by jbednar** [comment]
Thanks.

**Comment by ceball** [comment]
Thanks to @jakirkham, pyct is already on c-f, so I've now made the PR for updating datashader (https://github.com/conda-forge/datashader-feedstock/pull/4). However, as I commented there:

> Have just realized a test dependency (nbsmoke) is missing from conda-forge. I could disable that test, but I'd rather get the dependency itself onto conda-forge. So I'll make a new staged recipe for it...

I'll do that tomorrow.

**Comment by ceball** [comment]
I've now added a staged-recipe for nbsmoke: https://github.com/conda-forge/staged-recipes/pull/5987

**Comment by ceball** [comment]
I'll close this issue because https://github.com/conda-forge/datashader-feedstock/pull/4 should be ready after the tests finish (and any further necessary discussion can happen there).
