### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by philippjfr** [bokeh/datashader#606]
Someone just pointed out that at bottom of this page in the documentation: http://datashader.org/getting_started/2_Pipeline.html, the ``next notebook`` link is broken.

**Comment by jbednar** [comment]
Yes, that's the only fix needed, though the website won't update until I rebuild it manually, as it needs too many large files to rebuild automatically.

**Comment by jbednar** [comment]
I've fixed the text on datashader master, but I'm not sure when I'll next rebuild the website.  Thanks for raising the issue!
