### ISSUE TITLE
Datashader incompatible with dask>=0.18

### ISSUE THREAD

**Issue by philippjfr** [bokeh/datashader#613]
When running datashader with latest dask (>=0.18) using a dask dataframe datashader breaks:

```python
import numpy as np
import pandas as pd
import datashader as ds
import dask.dataframe as dd

df = pd.DataFrame(np.random.rand(1000, 2), columns=['x', 'y'])
ddf = dd.from_pandas(df, npartitions=2)
cvs = ds.Canvas(x_range=(0, 1), y_range=(0, 1), plot_width=100, plot_height=100)
cvs.points(ddf, 'x', 'y', agg=ds.count())
```

```
~/datashader/datashader/utils.py in __call__(self, head, *rest, **kwargs)
     56         typ = type(head)
     57         if typ in lk:
---> 58             return lk[typ](head, *rest, **kwargs)
     59         for cls in getmro(typ)[1:]:
     60             if cls in lk:

~/datashader/datashader/dask.py in dask_pipeline(df, schema, canvas, glyph, summary)
     19     dsk, name = glyph_dispatch(glyph, df, schema, canvas, summary)
     20 
---> 21     get = _globals['get'] or getattr(df, '__dask_scheduler__', None) or df._default_get
     22     keys = getattr(df, '__dask_keys__', None) or df._keys
     23     optimize = getattr(df, '__dask_optimize__', None) or df._optimize

KeyError: 'get'
```

**Comment by philippjfr** [comment]
I haven't done much digging but this might be related to: https://github.com/dask/dask/issues/3448 Ping @mrocklin or @jcrist in case you know offhand what caused this and how to fix it.

**Comment by mrocklin** [comment]
I'll take a look in a bit

**Comment by mrocklin** [comment]
This should work short term.  Long term you should consider using `dask.config.get` (see http://matthewrocklin.com/blog/work/2018/06/14/dask-0.18.0) or maybe `dask.base.get_scheduler`

```diff
diff --git a/datashader/dask.py b/datashader/dask.py
index 25b840e..dc933e9 100644
--- a/datashader/dask.py
+++ b/datashader/dask.py
@@ -18,7 +18,7 @@ __all__ = ()
 def dask_pipeline(df, schema, canvas, glyph, summary):
     dsk, name = glyph_dispatch(glyph, df, schema, canvas, summary)
 
-    get = _globals['get'] or getattr(df, '__dask_scheduler__', None) or df._default_get
+    get = _globals.get('get') or getattr(df, '__dask_scheduler__', None) or df._default_get
     keys = getattr(df, '__dask_keys__', None) or df._keys
     optimize = getattr(df, '__dask_optimize__', None) or df._optimize
 
```

**Comment by philippjfr** [comment]
Thanks for the quick reply. Might do that immediately and do a version check for backward compatibility.

**Comment by mrocklin** [comment]
dask.config.get will require dask.__version__ >= 0.18.0 , which was
released a couple weeks ago

**Comment by stevencollinscn** [comment]
@philippjfr 
Get the same issue with a csv file and tested with the code you provided above. The Issue exists wtih `dask 1.0.0`.

![image](https://user-images.githubusercontent.com/33796896/50467977-abd0fd00-0973-11e9-942c-a5e8437ad093.png)

**Comment by stevencollinscn** [comment]
It seems like I have some trouble with `pip` install and just updated `datashader` to `0.6.8` and it's working now. Sorry about that.

`conda install -c conda-forge datashader`
