### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by ceball** [bokeh/datashader#620]
Some time in the last 10 days, datashader tests have started failing (at least on linux - other platforms unknown at the moment):

<img width="863" alt="screen shot 2018-07-18 at 6 44 43 pm" src="https://user-images.githubusercontent.com/1929/42898325-be954af0-8aba-11e8-83da-0e639b1933a5.png">

(https://travis-ci.org/bokeh/datashader/jobs/405422999)

This issue's just to note it for now - haven't investigated.

**Comment by mcepl** [comment]
I have more of these:

 * test_log_axis_points
 * test_log_axis_line
 * test_log_axis_points
 * test_log_axis_line

Build log is [osc-build-log.txt](https://github.com/bokeh/datashader/files/2210105/osc-build-log.txt)

**Comment by ceball** [comment]
(I know what's likely to be relevant for our own builds, which is that numba 0.39.0 made it onto anaconda defaults 6 days ago...and I see you also have numba 0.39.0.)

**Comment by ceball** [comment]
https://github.com/numba/numba/issues/3135
