### ISSUE TITLE
Restore manual installation information to README

### ISSUE THREAD

**Issue by birdsarah** [bokeh/datashader#67]
Hi,

We just had a user on the bokeh mailing list who couldn't install datashader - there's no win-64 package.

I went to point them to the manual install I used the other day, but it's gone from the README. 

Can you add it back? Other people who, want to hack on datashader for example, will still want the manual install information.

Or perhaps - given that you're already setup on RTD, then, it can just be in there under a dev guide?

**Comment by jbednar** [comment]
Good point.  For now, the old instructions can be found at:

https://github.com/bokeh/datashader/blob/deb0f1fc772576ad7a22e426ed9d04af1070cdce/README.md

We are currently building win64 packages.

**Comment by jcrist** [comment]
Conda packages are now available for windows 64, python 2.7 and 3.4. One of our dependencies doesn't support 3.5 on windows yet.

I also added instructions for installing from the repo to the readme in #68.
