### ISSUE TITLE
Add Census example

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#69]
The examples directory should have something demonstrating categorical data, and the 2010 Census data illustrates that nicely.  We'll need to add dynamic point sizing for it to work at high zoom levels, first...

**Comment by jcrist** [comment]
My qualm with using the census data is that it's rather large. In my opinion examples shouldn't take up multiple GB on disk. Census would be fine as a pre-run example (to show *how* to use the library to do a certain thing), but not necessarily a *runnable* example. We can almost certainly find (or create) a dataset that's much smaller, but still illustrates the concepts.

**Comment by jbednar** [comment]
The thing about the census data is that people are strongly motivated to try it out themselves -- they want to look at their own neighborhoods, zoom in and out of them, think of possible queries they could formulate, etc.  So while I agree that there should also be a very small example of categorical data, I think that making it simple to launch people into datashading Census data on their own is actually a very good advertisement for the library's capabilities and a natural way to get started with the library.  And hey, it's a library for working with large data, so it's hard to avoid using large data in the examples!

**Comment by jbednar** [comment]
I suppose we could make the default download be the tracts data, and leave the point-per-person data as something they have to deliberately uncomment.

**Comment by joelostblom** [comment]
Yes, I was just looking for this! Just a quick example of how to pass the different categories to either `create_image` or `csv_points` and how to individually color them would be very helpful. For my use case this would be useful without the point rescale at different zoom levels (although that would improve it further).

As an example, if I have a data frame with x- and y-coordinates and want to color the points not based on counts, but according to the row values of two columns, `col1` and `col2`, how would I modify the code snippet below? I tried adding a list of columns to `ds.mean` and an extra argument to `csv.points`, but it didn't work.

```python
import datashader as ds
from datashader import transfer_functions as tf
from functools import partial

def create_image(x_range, y_range, w, h, color_fn=tf.interpolate):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.points(df, 'x-coord',  'y-coord',  ds.mean('col1'))
    return image

create_image(x_range, y_range, 400, 250, color_fn=partial(tf.interpolate, low="lightgrey", high='black', how='log'))
```

**Comment by jcrist** [comment]
> As an example, if I have a data frame with x- and y-coordinates and want to color the points not based on counts, but according to the row values of two columns, col1 and col2, how would I modify the code snippet below?

What do you mean by "according to the row values of two columns"? In general, datashader creates pipelines for computing aggregates of data, and then transforming those aggregates into images. During the aggregate -> image step, we no longer have information on individual rows, but instead some statistic(s) about each pixel that we can use to map to colors. In the case of your code above, you're:

1. Mapping each row to a bin by `('x-coord', 'y-coord')`, and computing the mean of `'col1'` in each bin.
2. Transforming the resulting aggregate into an image by interpolating these means from `lightgrey` to `black` along a log scale.

If this wasn't a good enough explanation, please open a separate issue where we can help you further. We definitely need to improve our documentation.

**Comment by joelostblom** [comment]
Sorry, I was wondering if that wording would be unclear...

In addition to the two steps you mentions, I want to also compute the mean of `col2` and map those values to another color in the image, say `lightred` to `red`.

So the final image should display `col1` in a grayscale and `col2` in a colormap of red values. This is similar to how the census demo showed ethnicities in different colors.

I opened a [new issue here](https://github.com/bokeh/datashader/issues/71)
