### ISSUE TITLE
module named tile_providers missing from Bokeh?

### ISSUE THREAD

**Issue by tonyj4102** [bokeh/datashader#72]
Hi 

I am running a datashader demo developed by Continum Analytics here:
c

I am running the demo, but after loading BokehJS, it seems the module named tile_providers doesn't exist anymore?

Please advise

Thanks
TJ

Notebook: module named tile_providers

I'm now at the 3rd code segment in the Jupyter Notebook after receiving:

"BokehJS successfully loaded."

When I run the following code I received another error:

Code:

```python
from bokeh.tile_providers import STAMEN_TERRAIN

samples = df.sample(n=1000)
p = base_plot()
p.add_tile(STAMEN_TERRAIN)
p.circle(x=samples['dropoff_x'], y=samples['dropoff_y'], **options)
show(p)
```

Error:
```
---------------------------------------------------------------------------
ImportError Traceback (most recent call last)
<ipython-input-5-f4a971eece60> in <module>()
----> 1 from bokeh.tile_providers import STAMEN_TERRAIN
2
3 samples = df.sample(n=1000)
4 p = base_plot()
5 p.add_tile(STAMEN_TERRAIN)

ImportError: No module named tile_providers
```
Thanks

**Comment by tonyj4102** [comment]
[https://anaconda.org/jbednar/nyc_taxi/notebook](url)  <- Here is the link to the notebook

**Comment by jbednar** [comment]
`tile_providers` was introduced in Bokeh fairly recently, probably release 0.11, and if you have an earlier installation you'll need to update bokeh (e.g. run `conda install bokeh`).

**Comment by tonyj4102** [comment]
Thanks I ran conda install bokeh and have another error: ImportError: cannot import name transform_series

Please see below:

In [7]:

from bokeh.tile_providers import STAMEN_TERRAIN

​

samples = df.sample(n=1000)

p = base_plot()

p.add_tile(STAMEN_TERRAIN)

p.circle(x=samples['dropoff_x'], y=samples['dropoff_y'], **options)

show(p)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-f4a971eece60> in <module>()
----> 1 from bokeh.tile_providers import STAMEN_TERRAIN
      2 
      3 samples = df.sample(n=1000)
      4 p = base_plot()
      5 p.add_tile(STAMEN_TERRAIN)

/anaconda/lib/python2.7/site-packages/bokeh/tile_providers.py in <module>()
      2 
      3 '''
----> 4 from .models.tiles import WMTSTileSource
      5 
      6 #: Provide toner tiles from http://tile.stamen.com>

/anaconda/lib/python2.7/site-packages/bokeh/models/tiles.py in <module>()
      1 from __future__ import absolute_import
----> 2 from ..model import Model
      3 
      4 from ..core.properties import (Any, Dict, Float, String, Int, Bool)
      5 

/anaconda/lib/python2.7/site-packages/bokeh/model.py in <module>()
      8 from six import iteritems
      9 
---> 10 from .core.json_encoder import serialize_json
     11 from .core.properties import Any, HasProps, List, MetaHasProps, String
     12 from .core.query import find

anaconda/lib/python2.7/site-packages/bokeh/core/json_encoder.py in <module>()
     16 from ..settings import settings
     17 from ..util.dependencies import import_optional
---> 18 from ..util.serialization import transform_series, transform_array
     19 
     20 pd = import_optional('pandas')

ImportError: cannot import name transform_series

**Comment by bryevdv** [comment]
@tonyj4102 that function exists and has existed in Bokeh for a very long time:

https://github.com/bokeh/bokeh/blob/master/bokeh/util/serialization.py#L48

There is definitely something broken with your Bokeh installation. I would suggest creating an entirely new conda environment to test with.

**Comment by tonyj4102** [comment]
Thanks! I deleted all my bokeh folders and re-installed Bokeh.

I also had to run conda install -c https://conda.anaconda.org/anaconda ipykernel

**Comment by jbednar** [comment]
Sounds good!
