### ISSUE TITLE
Add a GMapPlot example

### ISSUE THREAD

**Issue by endafarrell** [bokeh/datashader#73]
It's unclear how to overlay a datashaded plot over a GMapPlot background and have both stay in sync on pan/zoom: an example would be really useful.

**Comment by brendancol** [comment]
hey @endafarrell 

You may want to instead use the `TileRenderer` classes in bokeh.  Can you post your example and I give you tips on modifying...

The `TileRenderer` class takes a `TileSource` which can wrap many different types of tile providers including gmaps.

**Comment by brendancol** [comment]
adding issue to bokeh repo as this is a `GMapPlot` + `Image Overlay` issue, not a datashader issue.
