### ISSUE TITLE
datashader Anacoder demo code: 2 errors numpy.core.multiarray failed to import, cannot import name config

### ISSUE THREAD

**Issue by tonyj4102** [bokeh/datashader#75]
Hi - Making progress getting the datashader demo code to run so far :) , except...  ;(

Ref # [https://github.com/bokeh/datashader/issues/72#issuecomment-185412152](url)

Now at "10-million-point datashaded plots: auto-ranging, but not perceptually calibrated" step @
[https://anaconda.org/jbednar/nyc_taxi/notebook ](url)

import datashader as ds
from datashader import transfer_functions as tf
from functools import partial

def create_image(x_range, y_range, w, h, color_fn=tf.interpolate):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.points(df, 'dropoff_x',  'dropoff_y',  ds.count('passenger_count'))
    image = color_fn(agg)
    return image

I am receiving these two errors.  Any guidance on this please? I ran "pip install numpy"  just in case and received the message: " Requirement already satisfied" 

Many Thanks.

Error#1 of 2:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version a but this version of numpy is 9

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-bc398173cd4c> in <module>()
----> 1 import datashader as ds
      2 from datashader import transfer_functions as tf
      3 from functools import partial
      4 
      5 def create_image(x_range, y_range, w, h, color_fn=tf.interpolate):

anaconda/lib/python2.7/site-packages/datashader/__init__.py in <module>()
      3 __version__ = '0.1.0'
      4 
----> 5 from .core import Canvas
      6 from .reductions import (count, sum, min, max, mean, std, var, count_cat,
      7                          summary)

anaconda/lib/python2.7/site-packages/datashader/core.py in <module>()
      5 from odo import discover
      6 
----> 7 from .utils import Dispatcher, ngjit
      8 
      9 

anaconda/lib/python2.7/site-packages/datashader/utils.py in <module>()
      3 from inspect import getmro
      4 
----> 5 import numba as nb
      6 from datashape import Unit
      7 from datashape.predicates import launder

anaconda/lib/python2.7/site-packages/numba/__init__.py in <module>()
      5 import re
      6 
----> 7 from . import testing, decorators
      8 from . import errors, special, types, config
      9 

anaconda/lib/python2.7/site-packages/numba/decorators.py in <module>()
      8 from . import config, sigutils
      9 from .errors import DeprecationError
---> 10 from .targets import registry
     11 from . import cuda
     12 

anaconda/lib/python2.7/site-packages/numba/targets/registry.py in <module>()
      1 from __future__ import print_function, division, absolute_import
      2 
----> 3 from . import cpu
      4 from .descriptors import TargetDescriptor
      5 from .. import dispatcher, utils, typing

anaconda/lib/python2.7/site-packages/numba/targets/cpu.py in <module>()
      9 from numba import _dynfunc, config
     10 from numba.callwrapper import PyCallWrapper
---> 11 from .base import BaseContext, PYOBJECT
     12 from numba import utils, cgutils, types
     13 from numba.utils import cached_property

anaconda/lib/python2.7/site-packages/numba/targets/base.py in <module>()
     13 
     14 from numba import types, utils, cgutils, typing
---> 15 from numba import _dynfunc, _helperlib
     16 from numba.pythonapi import PythonAPI
     17 from numba.targets.imputils import (user_function, user_generator,

ImportError: numpy.core.multiarray failed to import

Error#2 of 2:

Then after running the same code/cell again in jupyter I receive this error message:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-bc398173cd4c> in <module>()
----> 1 import datashader as ds
      2 from datashader import transfer_functions as tf
      3 from functools import partial
      4 
      5 def create_image(x_range, y_range, w, h, color_fn=tf.interpolate):

anaconda/lib/python2.7/site-packages/datashader/__init__.py in <module>()
      3 __version__ = '0.1.0'
      4 
----> 5 from .core import Canvas
      6 from .reductions import (count, sum, min, max, mean, std, var, count_cat,
      7                          summary)

anaconda/lib/python2.7/site-packages/datashader/core.py in <module>()
      5 from odo import discover
      6 
----> 7 from .utils import Dispatcher, ngjit
      8 
      9 

anaconda/lib/python2.7/site-packages/datashader/utils.py in <module>()
      3 from inspect import getmro
      4 
----> 5 import numba as nb
      6 from datashape import Unit
      7 from datashape.predicates import launder

anaconda/lib/python2.7/site-packages/numba/__init__.py in <module>()
      5 import re
      6 
----> 7 from . import testing, decorators
      8 from . import errors, special, types, config
      9 

anaconda/lib/python2.7/site-packages/numba/decorators.py in <module>()
      6 import warnings
      7 
----> 8 from . import config, sigutils
      9 from .errors import DeprecationError
     10 from .targets import registry

ImportError: cannot import name config

**Comment by jbednar** [comment]
I suspect you've got some different versions of numpy installed in different places.  E.g. if you do ``python -c "import numpy;print numpy.version;print numpy.file";``, I think it needs to be at least 1.8 for multiarray to be available.  Perhaps if you're combining pip and conda, one of them has gotten confused?

**Comment by tonyj4102** [comment]
Thanks for your reply I typed print numpy.version.version in jupyter where I am running the code, and got back 1.9.2

I also have 1.10 and 1.10.4 installed?

**Comment by tonyj4102** [comment]
Also not sure I understand what you mean by pip and conda being confused?

**Comment by jbednar** [comment]
By pip and conda being confused, I just meant that you mentioned installing something using pip, while the datashader instructions say to use conda, and I was theorizing (with no data! :-) that perhaps something got mixed up between those two package-management systems.  I myself tend to stick to conda for everything that's available on conda (like numpy), which works very smoothly.  I think multiarray should be available in both numpy 1.9 and 1.10, so I can't see what the problem might be.  But it looks like a problem with numpy or numba, not datashader per se.   If nothing else worked, I'd try a fresh conda install on a different machine or at least in a different environment.

**Comment by tonyj4102** [comment]
Okay I'll give that a shot. Thanks.

**Comment by jbednar** [comment]
I'll assume that worked and close this, but if it's still an issue, please re-open this and provide additional details.

**Comment by tonyj4102** [comment]
I reinstalled OSX and am going to try it again.  Hopefully there won't be any conflicts  with my Python installs this time. Thx
