### ISSUE TITLE
Allow usage of external colormaps, e.g. from matplotlib

### ISSUE THREAD

**Issue by pzwang** [bokeh/datashader#81]
It would be nice if `interpolate()` had knowledge of palettes to range over, instead of requiring a low and high color value.  This should be a fairly straightforward thing to do, but will just require a brief survey of what currently exists and the best way to incorporate the possibilities.  (e.g. https://bids.github.io/colormap/)

**Comment by jbednar** [comment]
@jcrist and I have discussed ways to support this easily.  I sent him some sample code in C from an earlier project of mine that makes it trivial to specify arbitrarily complex colormaps, and he said he already had some code of his own that was similar, and would be able to put that in.  Too many things that need doing at once, though!

**Comment by pzwang** [comment]
Actually I think that we should be able to just grab in the colormaps from matplotlib (http://matplotlib.org/examples/color/colormaps_reference.html) and modify `interpolate()` to take a `cmap` kwarg that just defines one of these.  I'm hacking up a simple implementation right now.

**Comment by jbednar** [comment]
Yes, I think we should support that as well; they are complementary approaches.

**Comment by jbednar** [comment]
Odd; I think waffle.io changed the title back after I changed it!
