### ISSUE TITLE
Plots with a black background

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#82]
I'd like to be able to render images that have a black background, but I don't see how to do it.  The [`PIL.Image.fromarray`](http://pillow.readthedocs.org/en/3.1.x/reference/Image.html#PIL.Image.fromarray) function that we're using in `transfer_functions.py` generates an RGBA image, but the function call doesn't seem to allow the background color that comes through for transparent pixels to be specified.  Presumably we could make a blank black image using `PIL.Image.new` and then add the two images together, but that seems awkward...

**Comment by jcrist** [comment]
We produce images with a transparent background, so the best way would be to just overlay the image over some background using whatever plotting library datashader is being used with (e.g. [bokeh](http://bokeh.pydata.org/en/latest/docs/reference/models/plots.html#bokeh.models.plots.Plot.background_fill_color)). If you *really* want to make a png with a dark background, you can do that as shown in the last cell [here](https://gist.github.com/jcrist/62b366727886561356d8).

**Comment by jbednar** [comment]
What I was after was a way to specify the background color to be used when there is nothing behind the image, i.e. the bKGD chunk in the PNG specification: https://www.w3.org/TR/PNG/#12Alpha-channel-creation

But now that I think more clearly about it, where I actually want to use this is within a Jupyter notebook, where there *is* something behind the image, i.e. the color of the web page.  So the bKGD may well be already set to black (as some parts of the PIL docs suggest), and it's just correctly being ignored so that images can be composited with the underlying web page. So I think your suggestion of explicitly compositing the image with a specified background color (eliminating the alpha channel at that point) is probably what I want.  Thanks!

**Comment by jbednar** [comment]
Unfortunately, I haven't been able to get the proposed approach to work; I seem to be missing something.  The code @jcrist linked to is:

```python
import datashader.composite as ops
darkgrey = np.uint32(0xff0c0c0c)
ops.source(img, darkgrey)
```

But there's no module datashader.composite...

**Comment by jcrist** [comment]
Sure there is: https://github.com/bokeh/datashader/blob/master/datashader/composite.py. I suspect you aren't working off of git master.

**Comment by jbednar** [comment]
Too true!

**Comment by jbednar** [comment]
That works now, thanks.  In any case, I reopened it to propose that we add this as an option to interpolate, as in:

```python
tf.interpolate(agg, low="black", high='yellow', how='log', bg='black')
```

Because of how we pass around interpolate and create_image, it's awkward to apply the background after the fact, making non-white-background images much more clumsy to work with.  Any objection to extending interpolate like that?

**Comment by jcrist** [comment]
As I said above, we produce images that have 0 alpha where there's no data. You can overlay these images over a background after they're created, which seems to me to be a cleaner way of handling this. In bokeh, this is just a setting on the initial figure created:

```python
p = bp.figure(plot_width=600, plot_height=350, background_fill_color='black',
              x_range=x_range, y_range=y_range)
p.image_rgba(...)
```

If this doesn't satisfy your needs, setting the background in `interpolate` would be fine. This complicates image manipulations though, as all pixels will be non-empty then. Composing images with `stack`, or spreading pixels with `spread` will no longer work appropriately.

**Comment by jbednar** [comment]
Right; I don't think this is useful for Bokeh, just for the bare-image case, as is extensively used in our nyc_taxi notebooks and likely to be used in other notebooks in practice.  Notebooks typically default to light-color page backgrounds, and without compositing, such images are currently unusable:

![image](https://cloud.githubusercontent.com/assets/1695496/13469649/fc928718-e06d-11e5-98e0-f362200edeef.png)

They work fine after compositing:

![image](https://cloud.githubusercontent.com/assets/1695496/13469673/18509b20-e06e-11e5-88df-7ed4ed67084d.png)

But it's a pain to composite them manually each time, which will discourage people from using dark backgrounds in practice, hence the proposal for the option to fold this bit of complexity into interpolate.  That also gives us a place to document the pros and cons of adding such a background color, such as the reduced ability to later stack such images.

**Comment by jbednar** [comment]
Dang; I just noticed that you mentioned spreading wouldn't work after this.  :-( 

That greatly complicates the matter, because spreading is very much a case where I'd also want a black background, and I don't want to have to add such an option to spread, too.

Yet I don't think we can ask people to change the background color on their notebooks, just for this.  Now I don't know what to suggest, so that it can be less awkward.

**Comment by jbednar** [comment]
Trying to come up with some ways to make this less awkward and more obvious, if it can't be as simple as `bg='black'`...

I guess at a minimum we'd want `source` to accept a string color like we use everywhere else, but I don't see a function in colors.py that would help achieve that; those return a triple, not a uint32 as apparently expected by `source()`.  

The name `source` also doesn't convey anything to me that would make it come to mind for this purpose; I'd expect a binary function `def source(src, dst)` to be defined as `return src`, not "return src if alpha channel is nonzero, else dest".  I'd suggest `overlay`, but that's probably what `over` is for, just respecting alpha more precisely by mixing.  Maybe `occlude`?  That still seems very non-obvious.  The obvious `set_background` won't work, of course, since `source` can be used for two images, not just a bg color.

**Comment by jbednar** [comment]
That's definitely less awkward to use, thanks.  Maybe call it `set_bg`, if this is to be used often. It should probably have a default color=None, which is a no-op, to make it easier to use in a pipeline.  I *think* at that point then I can just add it to the various pipelines in nyc_taxi.ipynb, safely doing nothing unless the bg is explicitly selected, and similarly for spreading (where it can go after the spreading step, again usually a no-op).  Can you make a quick PR for that, then?

**Comment by jbednar** [comment]
The result is that instead of my proposed:

```
tf.interpolate(agg, low="black", high='yellow', how='log', bg='black')
```

we end up with the nearly as concise but much more composable:

```python
tf.set_bg(tf.interpolate(agg, low="black", high='yellow', how='log'), 'black')
```

**Comment by jcrist** [comment]
Pr submitted. Just to clarify something you said above:

> The name source also doesn't convey anything to me...

The compositing operators use the standard names, as originally defined in the classic [Porter/Duff paper](http://keithp.com/~keithp/porterduff/p253-porter.pdf). These are common in almost [every](http://cairographics.org/operators/) [graphics](https://www.w3.org/TR/SVGCompositing/#alphaCompositing) [package](http://developer.android.com/reference/android/graphics/PorterDuff.Mode.html). I'd be very reluctant to change their names. That said, they're also relatively low level - I wouldn't expect a user to interact with them directly.

**Comment by jbednar** [comment]
The names are clear in some contexts, but not others; depends whether one is thinking about the alpha channel explicitly, or about images in general.  In this case, set_bg is much clearer for the uses we've outlined here.
