### ISSUE TITLE
HTTP request sent; waiting for response.

### ISSUE THREAD

**Issue by apaytuvi** [bokeh/datashader#84]
I have executed

`python dashboard/dashboard.py --config dashboard/nyc_taxi.yml`

to see the example, but it does not return anything. Well... yes, this and only this:

`HTTP request sent; waiting for response`

There's nothing in `localhost:5000`.

**Comment by brendancol** [comment]
hey @apaytuvi A couple questions:
- Have you downloaded the nyc_taxi dataset?  
- Do you see any error messages in the console running the server?
- Also, on the first load, it will take some time to load data into memory. Subsequent requests will be fast.

**Comment by jbednar** [comment]
Maybe first try the nyc_taxi.ipynb notebook, which doesn't spawn a separate server and thus is probably easier to debug.  If that works but the dashboard doesn't, let us know!

**Comment by apaytuvi** [comment]
Well, the problem was that I was working on a server and it was stuck at:

`webbrowser.open('http://localhost:{}'.format(APP_PORT))`

Once I commented this line, everything worked fine. Thanks!

**Comment by brendancol** [comment]
ok cool.  Yeah I'm going to add a try/except block to handle that.  Thanks.
