### ISSUE TITLE
Raster/gridded-data support in datashader

### ISSUE THREAD

**Issue by thoth291** [bokeh/datashader#86]
I posted this question quite few days ago but is looks like it dragged no attention.
https://github.com/bokeh/bokeh-notebooks/issues/24

In two sentences:
remote_ocean_slider example from here ( https://github.com/bokeh/bokeh-notebooks/blob/master/quickstart/quickstart.ipynb ) is not implemented in Datashader.
Is it actually possible?

It looks like Datashader is only for Scatter and Line plots...
What about Image (2D) data?

In my case the data slices has about 1B points, but the resolution on the client side is far less than that.
The client side also will navigate through the data and apply some operations (filtering, scaling, interleaving and colormapping) on the selected section.

I plan to implement it as a widget so that I can use it in all of my post/pre-processing activities...

Any reply is highly appreciated!
Thanks!

**Comment by brendancol** [comment]
You're correct. At the moment there is only support for points and lines.  Having a `Canvas.image()` would be great. I'll discuss with the team and get back to you.

**Comment by jbednar** [comment]
See discussion at https://github.com/bokeh/bokeh-notebooks/issues/24 ; I answered there because the ocean slider example is a Bokeh example, not one from datashader.  I'll rename this issue and keep it here, though, because raster support is definitely something we will be adding to datashader.

**Comment by brendancol** [comment]
`datashader.Canvas` now supports rasters as input using `rasterio`.  Any raster format supported by GDAL should work (tif, img, grid, etc.).  The raster feature basically skips the aggregate stage of the datashader pipeline and returns an aggregate object which can be used with subsequent transfer functions or for filtering a scatter/line aggregate.
