### ISSUE TITLE
Hover tool support

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#91]
Because datashader produces an image rather than a collection of glyphs, there is no direct information available to the plotting program about the precise numerical values of plotted data.  This information can be made available separately from the image, in a way that a plotting program (e.g. Bokeh) can display using the "hover" or "tooltips" mechanism, revealing values corresponding to the current mouse pointer location.  At a minimum this information could just be the numerical value of that pixel, but it can be expanded to include counts and minimum/maximum values (if e.g. average or total values are being plotted), various statistical measures, etc.  

It may be useful to bin this information on a grid coarser than the aggregation grid, which simply involves a pass over the aggregate grid to merge adjacent cells' data.  In this case, it would be helpful if the hover tool showed the outline of the grid cell whose data is being shown, for clarity.

Tasks (may need to be expanded):

- [x] Implement fixed example of making information visible by hovering
- [ ] Decide on an API for making the information available from the pipeline in general
- [ ] Extend InteractiveImage to make use of data other than the image itself, perhaps by optionally accepting a dictionary or tuple, and grabbing the `image` key's value in that dictionary
- [x] Update some of the examples to include hover information

Some of this implementation may overlap with the support for color keys/legends in issue #90, in that it requires the underlying library to make information available about the data shown in an image.

**Comment by apaytuvi** [comment]
I'm not too much into the project's code, but I can help if you want.

**Comment by jbednar** [comment]
@apaytuvi, thanks!  We'll certainly need testers, in any case, and would love to have feedback!

**Comment by tommycarstensen** [comment]
Has this been implemented? I'm happy to be a tester.
