### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by jdupl123** [bokeh/datashader#96]
I tried modifying the nyc-taxi example to work with some of my own data. 

when i run ~/anaconda3/bin/bokeh serve --show datashaderDataAnalysis.py 

I get two exceptions. 

File "dispatcher.py", line 710, in _open_for_write:
with open(tmpname, "wb") as f: Traceback (most recent call last):
  File "/home/jduplessis/anaconda3/lib/python3.5/site-packages/numba/dispatcher.py", line 657, in save_overload
    data_name = overloads[key]
KeyError: ('(uint32,)', ('x86_64-unknown-linux-gnu', 'core-avx2', True))

and 

  File "/home/jduplessis/anaconda3/lib/python3.5/site-packages/numba/dispatcher.py", line 710, in _open_for_write
    with open(tmpname, "wb") as f:
PermissionError: [Errno 13] Permission denied: '/home/jduplessis/anaconda3/lib/python3.5/site-packages/datashader-0.1.0-py3.5.egg/datashader/__pycache__/composite.extract_scaled-10.py35m.nbi.tmp.8249'

any ideas?

**Comment by jdupl123** [comment]
upgrading numba seemed to fix this issue

**Comment by jbednar** [comment]
Perfect, thanks!  Can you let us know which versions did and did not work, so that we can update our list of required packages?

**Comment by jdupl123** [comment]
I had the default anaconda install which appear to be 0.23.1 I now have (0.24.0) which is working.

**Comment by jbednar** [comment]
Can you tell me the *numba* versions that did and did not work?

**Comment by jdupl123** [comment]
0.23.1 is the _numba_ version i had which did not work and 0.24.0 is the _numba_ version which is working now.

**Comment by jbednar** [comment]
Perfect; thanks!  I thought you were saying those were the Anaconda version numbers. :-)  I'll add that info to the requirements.
